In [103]:
import pandas as pd
import numpy as np
import plotly.express as px
import scipy.stats as stats
from scipy import stats
import statsmodels.api as sm
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
from scipy.stats import shapiro, chi2_contingency
import datetime

In [104]:
df1 = pd.read_csv('cleaned_imdb_2024.csv')
df1

,Home_Page,Movie_Name,Genres,Overview,Cast,Original_Language,Storyline,Production_Company,Release_Date,Tagline,Vote_Average,Vote_Count,Budget_USD,Revenue_$,Run_Time_Minutes,Release_Country
0,https://www.imdb.com/title/tt5040012/,Nosferatu,"['Fantasy', 'Horror', 'Mystery']",A gothic tale of obsession between a haunted y...,"['Lily-Rose Depp', 'Nicholas Hoult', 'Bill Ska...","['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,"['Focus Features', 'Maiden Voyage Pictures', '...",2024-12-25,Succumb to the darkness.,7.3,151K,$50.0M,$176.0M,132,United States
1,https://www.imdb.com/title/tt20221436/,Emilia Pérez,"['Comedy', 'Crime', 'Drama', 'Musical', 'Thril...",Emilia Pérez follows three remarkable women in...,"['Zoe Saldaña', 'Karla Sofía Gascón', 'Selena ...","['Spanish', 'English']","In modern-day Mexico, overqualified and exploi...","['Why Not Productions', 'Page 114', 'Pathé']",2024-11-13,Not_Found,5.5,71K,$27.3M,$15.0M,132,United States
2,https://www.imdb.com/title/tt8999762/,The Brutalist,['Drama'],When a visionary architect and his wife flee p...,"['Adrien Brody', 'Felicity Jones', 'Guy Pearce...","['English', 'Hungarian', 'Italian', 'Hebrew', ...",When visionary architect László Toth and his w...,"['Brookstreet Pictures', 'Kaplan Morrison', 'I...",2025-01-24,Welcome to America.,7.9,28K,$10.0M,$31.1M,214,Canada
3,https://www.imdb.com/title/tt27657135/,Saturday Night,"['Biography', 'Comedy', 'Drama', 'History']","At 11:30pm on October 11th, 1975, a ferocious ...","['Gabriel LaBelle', 'Rachel Sennott', 'Cory Mi...",['English'],"At 11:30pm on October 11, 1975, a ferocious tr...","['Columbia Pictures', 'TSG Entertainment']",2024-10-11,"October 11, 1975, The First Saturday Night Liv...",7.0,26K,$25.0M,$10.0M,109,United States
4,https://www.imdb.com/title/tt17526714/,The Substance,"['Drama', 'Horror', 'Sci-Fi']",A fading celebrity takes a black-market drug: ...,"['Demi Moore', 'Margaret Qualley', 'Dennis Qua...",['English'],Have you ever dreamed of a better version of y...,"['Working Title Films', 'A Good Story', 'Black...",2024-09-20,"If you follow the instructions, what could go ...",7.3,249K,$17.5M,$77.0M,141,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,https://www.imdb.com/title/tt28288478/,The Cage,"['Biography', 'Drama', 'Sport']","Dreaming of going pro, a young fighter struggl...","['Franck Gastambide', 'Melvin Boomer', 'Bosh',...",['French'],"Dreaming of going pro, a young fighter struggl...",['Ondamax Films'],2024-11-08,Fight for your dreams.,6.5,2.3K,$0,$0,45,United States
497,https://www.imdb.com/title/tt20519854/,The Man Who Could Not Remain Silent,"['Short', 'Drama']","1993, Bosnia and Herzegovina. A passenger trai...","['Dragan Micanovic', 'Goran Bogdan', 'Alexis M...",['Croatian'],"1993, Bosnia and Herzegovina. A passenger trai...","['Antitalent Produkcija', 'Contrast Films', 'L...",2025-01-16,Not_Found,7.4,1.3K,$0,$0,13,Croatia
498,https://www.imdb.com/title/tt28349451/,The Shadow Strays,"['Action', 'Crime', 'Thriller']","Codename 13, a 17-year-old assassin, is suspen...","['Aurora Ribero', 'Hana Malasan', 'Taskya Namy...","['Indonesian', 'English', 'Japanese', 'Chinese']","Codename 13, a 17-year-old trained assassin is...","['Frontier Pictures', 'XYZ Films']",2024-10-17,Not_Found,6.5,8.6K,$0,$0,144,United States
499,https://www.imdb.com/title/tt31609000/,Anthracite,"['Crime', 'Drama', 'Mystery', 'Thriller']",An old case is wrenched open when a reporter g...,"['Hatik', 'Noémie Schmidt', 'Camille Lou', 'Ni...",['French'],"In 1994, the collective suicide of a sect base...",['Mediawan'],2024-04-10,Not_Found,6.1,4.8K,$0,$0,50,United States
500,https://www.imdb.com/title/tt14203572/,Monsieur Spade,"['Crime', 'Drama', 'Thriller']",The famous detective Sam Spade is now 60 and l...,"['Clive Owen', 'Cara Bossom', 'Denis Ménochet'...","['English', 'French']",Monsieur Spade centers around the infamous pro...,"['Black Bear', 'Haut Et Court Tv']",2024-01-14,Not_Found,6.8,7.4K,$0,$0,Unknown,United States

In [105]:
df1.columns

Index(['Home_Page', 'Movie_Name', 'Genres', 'Overview', 'Cast',
       'Original_Language', 'Storyline', 'Production_Company', 'Release_Date',
       'Tagline', 'Vote_Average', 'Vote_Count', 'Budget_USD', 'Revenue_$',
       'Run_Time_Minutes', 'Release_Country'],
      dtype='object')

In [106]:
df1[df1['Movie_Name']=='Deadpool & Wolverine']

,Home_Page,Movie_Name,Genres,Overview,Cast,Original_Language,Storyline,Production_Company,Release_Date,Tagline,Vote_Average,Vote_Count,Budget_USD,Revenue_$,Run_Time_Minutes,Release_Country
54,https://www.imdb.com/title/tt6263850/,Deadpool & Wolverine,"['Action', 'Adventure', 'Comedy', 'Sci-Fi']",Deadpool is offered a place in the Marvel Cine...,"['Ryan Reynolds', 'Hugh Jackman', 'Emma Corrin...","['English', 'French', 'Spanish']",In this multiverse story Deadpool is approache...,"['Marvel Studios', '20th Century Studios', 'Ma...",2024-07-26,Everyone deserves a happy ending.,7.6,468K,$200.0M,$1.3B,128,United States

In [107]:
df1.head()

,Home_Page,Movie_Name,Genres,Overview,Cast,Original_Language,Storyline,Production_Company,Release_Date,Tagline,Vote_Average,Vote_Count,Budget_USD,Revenue_$,Run_Time_Minutes,Release_Country
0,https://www.imdb.com/title/tt5040012/,Nosferatu,"['Fantasy', 'Horror', 'Mystery']",A gothic tale of obsession between a haunted y...,"['Lily-Rose Depp', 'Nicholas Hoult', 'Bill Ska...","['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,"['Focus Features', 'Maiden Voyage Pictures', '...",2024-12-25,Succumb to the darkness.,7.3,151K,$50.0M,$176.0M,132,United States
1,https://www.imdb.com/title/tt20221436/,Emilia Pérez,"['Comedy', 'Crime', 'Drama', 'Musical', 'Thril...",Emilia Pérez follows three remarkable women in...,"['Zoe Saldaña', 'Karla Sofía Gascón', 'Selena ...","['Spanish', 'English']","In modern-day Mexico, overqualified and exploi...","['Why Not Productions', 'Page 114', 'Pathé']",2024-11-13,Not_Found,5.5,71K,$27.3M,$15.0M,132,United States
2,https://www.imdb.com/title/tt8999762/,The Brutalist,['Drama'],When a visionary architect and his wife flee p...,"['Adrien Brody', 'Felicity Jones', 'Guy Pearce...","['English', 'Hungarian', 'Italian', 'Hebrew', ...",When visionary architect László Toth and his w...,"['Brookstreet Pictures', 'Kaplan Morrison', 'I...",2025-01-24,Welcome to America.,7.9,28K,$10.0M,$31.1M,214,Canada
3,https://www.imdb.com/title/tt27657135/,Saturday Night,"['Biography', 'Comedy', 'Drama', 'History']","At 11:30pm on October 11th, 1975, a ferocious ...","['Gabriel LaBelle', 'Rachel Sennott', 'Cory Mi...",['English'],"At 11:30pm on October 11, 1975, a ferocious tr...","['Columbia Pictures', 'TSG Entertainment']",2024-10-11,"October 11, 1975, The First Saturday Night Liv...",7.0,26K,$25.0M,$10.0M,109,United States
4,https://www.imdb.com/title/tt17526714/,The Substance,"['Drama', 'Horror', 'Sci-Fi']",A fading celebrity takes a black-market drug: ...,"['Demi Moore', 'Margaret Qualley', 'Dennis Qua...",['English'],Have you ever dreamed of a better version of y...,"['Working Title Films', 'A Good Story', 'Black...",2024-09-20,"If you follow the instructions, what could go ...",7.3,249K,$17.5M,$77.0M,141,United States

In [108]:
df2 = df1

In [109]:
def clean_numeric(value):
    if isinstance(value, str):  # Проверяем, является ли значение строкой
        value = value.replace("$", "").replace(",", "").strip()  # Убираем знак доллара, запятые и пробелы
        
        if value.endswith("M"):  # Если строка заканчивается на 'M' (миллионы)
            return float(value.replace("M", "")) * 1_000_000  # Удаляем 'M' и умножаем на 1 миллион
        
        elif value.endswith("K"):  # Если строка заканчивается на 'K' (тысячи)
            return float(value.replace("K", "")) * 1_000  # Удаляем 'K' и умножаем на 1000

    try:
        return float(value)  # Преобразуем оставшееся значение в число
    except ValueError:  # Если преобразование не удалось (например, строка содержит нечисловые данные)
        return np.nan  # Возвращаем NaN (значение отсутствует)

In [110]:
# чистка столбцов с количеством голосов, бюджетом проекта, сборами и длительностью
df2["Vote_Count"] = df2["Vote_Count"].apply(clean_numeric)
df2["Budget_USD"] = df2["Budget_USD"].apply(clean_numeric)
df2["Revenue_$"] = df2["Revenue_$"].apply(clean_numeric)
df2["Run_Time_Minutes"] = df2["Run_Time_Minutes"].apply(pd.to_numeric, errors='coerce')
df2[(df2['Budget_USD'] != 0) & (df2['Revenue_$'].isna())]

,Home_Page,Movie_Name,Genres,Overview,Cast,Original_Language,Storyline,Production_Company,Release_Date,Tagline,Vote_Average,Vote_Count,Budget_USD,Revenue_$,Run_Time_Minutes,Release_Country
25,https://www.imdb.com/title/tt13622970/,Moana 2,"['Animation', 'Adventure', 'Comedy', 'Family',...",After receiving an unexpected call from her wa...,"[""Auli'i Cravalho"", 'Dwayne Johnson', 'Hualala...",['English'],After receiving an unexpected call from her wa...,"['Walt Disney Animation Canada', 'Walt Disney ...",2024-11-27,Find the way.,6.8,77000.0,150000000.0,NaN,100.0,United States
54,https://www.imdb.com/title/tt6263850/,Deadpool & Wolverine,"['Action', 'Adventure', 'Comedy', 'Sci-Fi']",Deadpool is offered a place in the Marvel Cine...,"['Ryan Reynolds', 'Hugh Jackman', 'Emma Corrin...","['English', 'French', 'Spanish']",In this multiverse story Deadpool is approache...,"['Marvel Studios', '20th Century Studios', 'Ma...",2024-07-26,Everyone deserves a happy ending.,7.6,468000.0,200000000.0,NaN,128.0,United States
122,https://www.imdb.com/title/tt22022452/,Inside Out 2,"['Animation', 'Adventure', 'Comedy', 'Drama', ...",A sequel that features Riley entering puberty ...,"['Amy Poehler', 'Maya Hawke', 'Kensington Tall...","['English', 'French', 'Spanish']",Teenager Riley's mind headquarters is undergoi...,"['Walt Disney Pictures', 'Pixar Animation Stud...",2024-06-14,Big changes. New emotions.,7.5,205000.0,200000000.0,NaN,96.0,United States

In [111]:
df2.loc[df2['Movie_Name'] == 'Deadpool & Wolverine', 'Revenue_$'] = 1210000000
df2.loc[df2['Movie_Name'] == 'Moana 2', 'Revenue_$'] = 1050000000
df2.loc[df2['Movie_Name'] == 'Inside Out 2', 'Revenue_$'] = 1698863816

In [112]:
df2[df2['Movie_Name']=='Deadpool & Wolverine']

,Home_Page,Movie_Name,Genres,Overview,Cast,Original_Language,Storyline,Production_Company,Release_Date,Tagline,Vote_Average,Vote_Count,Budget_USD,Revenue_$,Run_Time_Minutes,Release_Country
54,https://www.imdb.com/title/tt6263850/,Deadpool & Wolverine,"['Action', 'Adventure', 'Comedy', 'Sci-Fi']",Deadpool is offered a place in the Marvel Cine...,"['Ryan Reynolds', 'Hugh Jackman', 'Emma Corrin...","['English', 'French', 'Spanish']",In this multiverse story Deadpool is approache...,"['Marvel Studios', '20th Century Studios', 'Ma...",2024-07-26,Everyone deserves a happy ending.,7.6,468000.0,200000000.0,1.210000e+09,128.0,United States

In [113]:
df2[(df2['Revenue_$'].isna())]

Empty DataFrame
Columns: [Home_Page, Movie_Name, Genres, Overview, Cast, Original_Language, Storyline, Production_Company, Release_Date, Tagline, Vote_Average, Vote_Count, Budget_USD, Revenue_$, Run_Time_Minutes, Release_Country]
Index: []

In [114]:
df2[(df2['Budget_USD'] != 0) & (df2['Revenue_$'] == 0)]

,Home_Page,Movie_Name,Genres,Overview,Cast,Original_Language,Storyline,Production_Company,Release_Date,Tagline,Vote_Average,Vote_Count,Budget_USD,Revenue_$,Run_Time_Minutes,Release_Country
138,https://www.imdb.com/title/tt11301886/,Rebel Ridge,"['Action', 'Crime', 'Drama', 'Thriller']",A former Marine grapples his way through a web...,"['Aaron Pierre', 'Don Johnson', 'AnnaSophia Ro...",['English'],An ex Marine on his way to bail out his cousin...,"['Bonneville Pictures', 'Film Science']",2024-09-06,They brought the fight. He'll bring them down.,6.8,82000.0,28900000.0,0.0,131.0,United States
193,https://www.imdb.com/title/tt3359350/,Road House,"['Action', 'Drama', 'Thriller']",Ex-UFC fighter Dalton takes a job as a bouncer...,"['Jake Gyllenhaal', 'Daniela Melchior', 'Conor...",['English'],Dalton is middleweight fighter who is going th...,"['Metro-Goldwyn-Mayer (MGM)', 'Silver Pictures']",2024-03-21,Take it outside.,6.2,164000.0,85000000.0,0.0,121.0,United States
203,https://www.imdb.com/title/tt13452446/,Damsel,"['Action', 'Adventure', 'Fantasy']",A dutiful damsel agrees to marry a handsome pr...,"['Millie Bobby Brown', 'Ray Winstone', 'Angela...",['English'],"A young woman, Elodie, meets a handsome prince...","['Netflix', 'PCMA Management and Productions',...",2024-03-08,This is not a fairytale.,6.1,107000.0,70000000.0,0.0,110.0,United States
254,https://www.imdb.com/title/tt32117345/,The Intruder,['Thriller'],"A young, paranoid man begins to believe someon...","['David Gow', 'Steve McNair', 'Monica Bell', '...",['English'],"A young, paranoid man begins to believe someon...",['Not_Found'],2025-01-30,Not_Found,4.8,426.0,10000.0,0.0,101.0,Aruba
294,https://www.imdb.com/title/tt11097384/,Spaceman,"['Adventure', 'Drama', 'Sci-Fi']",Half a year into his solo mission on the edge ...,"['Adam Sandler', 'Carey Mulligan', 'Paul Dano'...",['English'],"An intergalactic odyssey of love, ambition, an...","['Free Association', 'Stillking Films', 'Tango...",2024-03-01,Not_Found,5.7,42000.0,40000000.0,0.0,107.0,United States
309,https://www.imdb.com/title/tt3083016/,Beverly Hills Cop: Axel F,"['Action', 'Comedy', 'Crime', 'Thriller']",Axel Foley returns to Beverly Hills after his ...,"['Eddie Murphy', 'Joseph Gordon-Levitt', 'Tayl...","['English', 'Spanish']",Detective Axel Foley is up to his usual tricks...,"['Don Simpson/Jerry Bruckheimer Films', 'Eddie...",2024-07-03,Not_Found,6.4,79000.0,150000000.0,0.0,118.0,United States
341,https://www.imdb.com/title/tt9271850/,The Inheritance,"['Horror', 'Thriller']","A billionaire on the eve of his 75th birthday,...","['Bob Gunton', 'Peyton List', 'Briana Middleto...",['English'],"A billionaire on the eve of his 75th birthday,...",['Paul Schiff Productions'],2024-07-12,Not_Found,4.7,2600.0,14000000.0,0.0,85.0,Brazil
349,https://www.imdb.com/title/tt14914430/,Unfrosted,"['Biography', 'Comedy', 'History']","In 1963 Michigan, business rivals Kellogg's an...","['Isaac Bae', 'Jerry Seinfeld', 'Chris Rickett...",['English'],"In 1963 Michigan, business rivals Kellogg's an...","['Columbus 81 Productions', 'Good One Producti...",2024-05-03,A Pop-Tart Will Rise,5.5,34000.0,14200000.0,0.0,97.0,United States
354,https://www.imdb.com/title/tt22075376/,Milk & Serial,"['Horror', 'Thriller']",A surprise birthday prank takes a turn for the...,"['Curry Barker', 'Cooper Tomlinson', 'Adlih Al...",['English'],A surprise birthday prank takes a turn for the...,['Not_Found'],2024-08-09,Not_Found,6.6,2300.0,800.0,0.0,62.0,United States
381,https://www.imdb.com/title/tt6001846/,Long Gone Heroes,"['Action', 'Crime', 'Drama', 'Mystery', 'Thril...",A special forces soldier who has given up coun...,"['Eden Brolin', 'Andy Garcia', 'Melissa Leo', ...",['English'],"Gunner, a special forces soldier who has witne...","['Coexistence Studios', 'Desment Studios', 'Fi...",2024-09-20,Not_Found,5.1,824.0,20000000.0,0.0,92.0,United States
399,https://www.imdb.com/title/tt13964390/,Under Paris,['Not_Found'],"To save Paris from a bloodbath, a grieving sci...","['Bérénice Bejo', 'Nassim Lyes', 'Léa Léviant'...","['French', 'English']",Not_Found,['Let Me Be'],2024-06-05,Not_Found,5.2,35000.0,27300000.0,0.0,104.0,United States
419,https://www.imdb.com/title/tt23137904/,Rebel Moon - Part Two: The Scargiver,['Not_Found'],Kora and surviving warriors prepare to defend ...,"['Sofia Boutella', 'Djimon Hounsou', 'Ed Skrei...",['English'],Not_Found,"['Grand Electric', 'The Stone Quarry']",2024-04-19,Not_Found,5.3,58000.0,83000000.0,0.0,122.0,United States
482,https://www.imdb.com/title/tt8964540/,Stream,['Horror'],The Keenan family's simple weekend getaway tru...,"['Jeffrey Combs', 'Charles Edwin Powell', 'Dan...",['Not_Found'],When Roy and Elaine Keenan realize their famil...,"['Fuzz on the Lens Productions', 'Laknar Enter...",2024-08-21,Put some skin in the game.,5.5,5800.0,650000.0,0.0,123.0,United States
495,https://www.imdb.com/title/tt11001074/,Rust,['Western'],A boy left to fend for himself and his younger...,"['Travis Fimmel', 'Frances Fisher', 'Alec Bald...",['English'],A 13-year-old boy left to fend for himself and...,"['BondIt Media Capital', 'Cavalry Media', 'El ...",2024-11-20,Not_Found,4.1,113.0,7000000.0,0.0,NaN,Poland

In [115]:
df2.loc[df2['Revenue_$'] == 0, 'Revenue_$'] = np.nan

In [116]:
df2.shape

(501, 16)

In [117]:
# Фильтруем данные, оставляя только те, где бюджет не равен 0 и не NaN
df_filtered = df2[(df2["Budget_USD"] > 0) & (df2["Revenue_$"].notna()) & (df2["Revenue_$"] > 0)]
df_filtered

,Home_Page,Movie_Name,Genres,Overview,Cast,Original_Language,Storyline,Production_Company,Release_Date,Tagline,Vote_Average,Vote_Count,Budget_USD,Revenue_$,Run_Time_Minutes,Release_Country
0,https://www.imdb.com/title/tt5040012/,Nosferatu,"['Fantasy', 'Horror', 'Mystery']",A gothic tale of obsession between a haunted y...,"['Lily-Rose Depp', 'Nicholas Hoult', 'Bill Ska...","['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,"['Focus Features', 'Maiden Voyage Pictures', '...",2024-12-25,Succumb to the darkness.,7.3,151000.0,50000000.0,176000000.0,132.0,United States
1,https://www.imdb.com/title/tt20221436/,Emilia Pérez,"['Comedy', 'Crime', 'Drama', 'Musical', 'Thril...",Emilia Pérez follows three remarkable women in...,"['Zoe Saldaña', 'Karla Sofía Gascón', 'Selena ...","['Spanish', 'English']","In modern-day Mexico, overqualified and exploi...","['Why Not Productions', 'Page 114', 'Pathé']",2024-11-13,Not_Found,5.5,71000.0,27300000.0,15000000.0,132.0,United States
2,https://www.imdb.com/title/tt8999762/,The Brutalist,['Drama'],When a visionary architect and his wife flee p...,"['Adrien Brody', 'Felicity Jones', 'Guy Pearce...","['English', 'Hungarian', 'Italian', 'Hebrew', ...",When visionary architect László Toth and his w...,"['Brookstreet Pictures', 'Kaplan Morrison', 'I...",2025-01-24,Welcome to America.,7.9,28000.0,10000000.0,31100000.0,214.0,Canada
3,https://www.imdb.com/title/tt27657135/,Saturday Night,"['Biography', 'Comedy', 'Drama', 'History']","At 11:30pm on October 11th, 1975, a ferocious ...","['Gabriel LaBelle', 'Rachel Sennott', 'Cory Mi...",['English'],"At 11:30pm on October 11, 1975, a ferocious tr...","['Columbia Pictures', 'TSG Entertainment']",2024-10-11,"October 11, 1975, The First Saturday Night Liv...",7.0,26000.0,25000000.0,10000000.0,109.0,United States
4,https://www.imdb.com/title/tt17526714/,The Substance,"['Drama', 'Horror', 'Sci-Fi']",A fading celebrity takes a black-market drug: ...,"['Demi Moore', 'Margaret Qualley', 'Dennis Qua...",['English'],Have you ever dreamed of a better version of y...,"['Working Title Films', 'A Good Story', 'Black...",2024-09-20,"If you follow the instructions, what could go ...",7.3,249000.0,17500000.0,77000000.0,141.0,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
385,https://www.imdb.com/title/tt14088510/,Tarot,['Horror'],When a group of friends recklessly violates th...,"['Harriet Slater', 'Adain Bradley', 'Jacob Bat...",['English'],When a group of friends recklessly violates th...,"['Screen Gems', 'Alloy Entertainment', 'Capsto...",2024-05-03,Your fate is in the cards.,4.8,30000.0,8200000.0,49300000.0,92.0,United States
387,https://www.imdb.com/title/tt13818368/,Fighter,"['Action', 'Drama']",A reckless yet brilliant squadron leader and h...,"['Hrithik Roshan', 'Deepika Padukone', 'Anil K...","['Hindi', 'English']",Group Captain Rakesh Jai Singh (Rocky) is assi...,"['Betterfly Films', 'Manomay Motion Pictures',...",2024-01-25,Not_Found,6.2,52000.0,3000000.0,3800000.0,166.0,India
403,https://www.imdb.com/title/tt21188080/,Lisa Frankenstein,['Not_Found'],A coming of RAGE love story about a teenager a...,"['Kathryn Newton', 'Liza Soberano', 'Jenna Dav...",['English'],Not_Found,['MXN Entertainment'],2024-02-09,Not_Found,6.1,27000.0,13000000.0,9900000.0,101.0,United States
432,https://www.imdb.com/title/tt4996328/,Ordinary Angels,['Not_Found'],Inspired by the incredible true story of a hai...,"['Hilary Swank', 'Alan Ritchson', 'Emily Mitch...",['English'],Not_Found,"['Kingdom Story Company', 'Green Hummingbird E...",2024-02-23,Not_Found,7.4,15000.0,13000000.0,20600000.0,118.0,United States
461,https://www.imdb.com/title/tt11240348/,The Exorcism,"['Horror', 'Thriller']",A troubled actor begins to exhibit a disruptiv...,"['Russell Crowe', 'Ryan Simpkins', 'Sam Worthi...",['English'],12-year-old Anthony faced sexual assault. He b...,"['Miramax', 'Outerbanks Entertainment']",2024-06-21,Not_Found,4.2,11000.0,22000000.0,12600000.0,95.0,United States

In [118]:
# график зависимости бюджета фильма от его сборов
fig = px.scatter(df_filtered, x="Budget_USD", y="Revenue_$", color="Revenue_$",
                 title="Зависимость бюджета от сборов",
                 labels={"Budget_USD": "Бюджет (USD)", "Revenue_$": "Сборы (USD)"},
                 hover_data=["Budget_USD", "Revenue_$"],
                 color_continuous_scale="Viridis") 

fig.show()

In [119]:
fig = px.scatter(df_filtered, x="Budget_USD", y="Revenue_$", color="Revenue_$",
                 title="бюджет от сборов",
                 labels={"Budget_USD": "Бюджет (USD)", "Revenue_$": "Сборы (USD)"},
                 hover_data=["Budget_USD", "Revenue_$"],
                 color_continuous_scale="Viridis",
                 trendline="ols")
fig.show()

In [120]:
fig = px.scatter(df_filtered, x="Budget_USD", y="Revenue_$", color="Revenue_$",
                 title="бюджет от сборов",
                 labels={"Budget_USD": "Бюджет (USD)", "Revenue_$": "Сборы (USD)"},
                 hover_data=["Budget_USD", "Revenue_$"],
                 color_continuous_scale="Viridis",
                 )

# Добавляем сглаживание LOWESS
lowess_smooth = sm.nonparametric.lowess(df_filtered["Revenue_$"], df_filtered["Budget_USD"], frac=0.3)  # frac - параметр сглаживания
fig.add_scatter(x=lowess_smooth[:, 0], y=lowess_smooth[:, 1], mode='lines', name='LOWESS Smoothing', line=dict(color='red'))

In [121]:
# тест Шапиро-Уилка на нормальность данных
alpha = 0.05
stats_x, p_value_x = stats.shapiro(df_filtered['Budget_USD'])
stats_y, p_value_y = stats.shapiro(df_filtered['Revenue_$'])
print(f'Для х: статистика = {stats_x}, p-value = {p_value_x}')
print(f'Для х: статистика = {stats_y}, p-value = {p_value_y}')

# Принятие решения на основе p-значения
if p_value_x < alpha:
    print("Выборка X не нормальна")
else:
    print("Нельзя отклонить нулевую гипотезу о нормальности для Х")
if p_value_y < alpha:
    print("Выборка Y не нормальна")
else:
    print("Нельзя отклонить нулевую гипотезу о нормальности для Y")

Для х: статистика = 0.8149666330321097, p-value = 3.755233906766943e-10
Для х: статистика = 0.6115272345652963, p-value = 2.9828513558046504e-15
Выборка X не нормальна
Выборка Y не нормальна

In [122]:
corr1, p_value1 = stats.spearmanr(df_filtered["Budget_USD"], df_filtered["Revenue_$"])
corr1

np.float64(0.7224175001918727)

In [123]:
p_value1

np.float64(3.3712339364298587e-18)

In [124]:
fig = px.scatter(df_filtered, x="Budget_USD", y="Vote_Average", color="Vote_Average",
                 title="Зависимость рейтинга от бюджета фильма",
                 labels={"Budget_USD": "Бюджет (USD)", "Vote_Average": "Средний рейтинг"},
                 hover_data=["Budget_USD", "Vote_Average"],
                 color_continuous_scale="Viridis")
fig.show()

In [125]:
# тест Шапиро-Уилка на нормальность данных
from scipy import stats
alpha = 0.05
stats_x, p_value_x = stats.shapiro(df_filtered['Budget_USD'])
stats_y, p_value_y = stats.shapiro(df_filtered['Vote_Average'])
print(f'Для х: статистика = {stats_x}, p-value = {p_value_x}')

print(f'Для х: статистика = {stats_y}, p-value = {p_value_y}')

# Принятие решения на основе p-значения
if p_value_x < alpha:
    print("Выборка X не нормальна")
else:
    print("Нельзя отклонить нулевую гипотезу о нормальности для Х")
if p_value_y < alpha:
    print("Выборка Y не нормальна")
else:
    print("Нельзя отклонить нулевую гипотезу о нормальности для Y")

Для х: статистика = 0.8149666330321097, p-value = 3.755233906766943e-10
Для х: статистика = 0.9413362326796842, p-value = 0.0001591896886312187
Выборка X не нормальна
Выборка Y не нормальна

In [126]:
corr2, p_value2 = stats.spearmanr(df_filtered["Budget_USD"], df_filtered["Vote_Average"])
corr2

np.float64(0.09454883954305597)

In [127]:
if p_value2 < alpha:
    print("Отвергаем нулевую гипотезу (есть зависимость между бюджетом и рейтингом).")
else:
    print("Не удалось отвергнуть нулевую гипотезу (нет доказанной зависимости).")

Не удалось отвергнуть нулевую гипотезу (нет доказанной зависимости).

In [128]:
fig = px.scatter(df_filtered, x="Budget_USD", y="Vote_Average", color="Vote_Average",
                 title=f"Зависимость рейтинга от бюджета (Корреляция Спирмена: {corr2:.3f})",
                 labels={"Budget_USD": "Бюджет (USD)", "Vote_Average": "Средний рейтинг"},
                 hover_data=["Budget_USD", "Vote_Average"],
                 color_continuous_scale="Viridis",
                 trendline="ols")  # Линейная регрессия

fig.show()

In [129]:
fig = px.scatter(df_filtered, x="Budget_USD", y="Vote_Average", color="Vote_Average",
                 title=f"Зависимость рейтинга от бюджета (Корреляция Спирмена: {corr2:.3f})",
                 labels={"Budget_USD": "Бюджет (USD)", "Vote_Average": "Средний рейтинг"},
                 hover_data=["Budget_USD", "Vote_Average"],
                 color_continuous_scale="Viridis",
                 ) 
lowess_smooth = sm.nonparametric.lowess(df_filtered["Vote_Average"], df_filtered["Budget_USD"], frac=0.3)  # frac - параметр сглаживания
fig.add_scatter(x=lowess_smooth[:, 0], y=lowess_smooth[:, 1], mode='lines', name='LOWESS Smoothing', line=dict(color='red'))

In [130]:
df = df1.copy()
df

,Home_Page,Movie_Name,Genres,Overview,Cast,Original_Language,Storyline,Production_Company,Release_Date,Tagline,Vote_Average,Vote_Count,Budget_USD,Revenue_$,Run_Time_Minutes,Release_Country
0,https://www.imdb.com/title/tt5040012/,Nosferatu,"['Fantasy', 'Horror', 'Mystery']",A gothic tale of obsession between a haunted y...,"['Lily-Rose Depp', 'Nicholas Hoult', 'Bill Ska...","['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,"['Focus Features', 'Maiden Voyage Pictures', '...",2024-12-25,Succumb to the darkness.,7.3,151000.0,50000000.0,176000000.0,132.0,United States
1,https://www.imdb.com/title/tt20221436/,Emilia Pérez,"['Comedy', 'Crime', 'Drama', 'Musical', 'Thril...",Emilia Pérez follows three remarkable women in...,"['Zoe Saldaña', 'Karla Sofía Gascón', 'Selena ...","['Spanish', 'English']","In modern-day Mexico, overqualified and exploi...","['Why Not Productions', 'Page 114', 'Pathé']",2024-11-13,Not_Found,5.5,71000.0,27300000.0,15000000.0,132.0,United States
2,https://www.imdb.com/title/tt8999762/,The Brutalist,['Drama'],When a visionary architect and his wife flee p...,"['Adrien Brody', 'Felicity Jones', 'Guy Pearce...","['English', 'Hungarian', 'Italian', 'Hebrew', ...",When visionary architect László Toth and his w...,"['Brookstreet Pictures', 'Kaplan Morrison', 'I...",2025-01-24,Welcome to America.,7.9,28000.0,10000000.0,31100000.0,214.0,Canada
3,https://www.imdb.com/title/tt27657135/,Saturday Night,"['Biography', 'Comedy', 'Drama', 'History']","At 11:30pm on October 11th, 1975, a ferocious ...","['Gabriel LaBelle', 'Rachel Sennott', 'Cory Mi...",['English'],"At 11:30pm on October 11, 1975, a ferocious tr...","['Columbia Pictures', 'TSG Entertainment']",2024-10-11,"October 11, 1975, The First Saturday Night Liv...",7.0,26000.0,25000000.0,10000000.0,109.0,United States
4,https://www.imdb.com/title/tt17526714/,The Substance,"['Drama', 'Horror', 'Sci-Fi']",A fading celebrity takes a black-market drug: ...,"['Demi Moore', 'Margaret Qualley', 'Dennis Qua...",['English'],Have you ever dreamed of a better version of y...,"['Working Title Films', 'A Good Story', 'Black...",2024-09-20,"If you follow the instructions, what could go ...",7.3,249000.0,17500000.0,77000000.0,141.0,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,https://www.imdb.com/title/tt28288478/,The Cage,"['Biography', 'Drama', 'Sport']","Dreaming of going pro, a young fighter struggl...","['Franck Gastambide', 'Melvin Boomer', 'Bosh',...",['French'],"Dreaming of going pro, a young fighter struggl...",['Ondamax Films'],2024-11-08,Fight for your dreams.,6.5,2300.0,0.0,NaN,45.0,United States
497,https://www.imdb.com/title/tt20519854/,The Man Who Could Not Remain Silent,"['Short', 'Drama']","1993, Bosnia and Herzegovina. A passenger trai...","['Dragan Micanovic', 'Goran Bogdan', 'Alexis M...",['Croatian'],"1993, Bosnia and Herzegovina. A passenger trai...","['Antitalent Produkcija', 'Contrast Films', 'L...",2025-01-16,Not_Found,7.4,1300.0,0.0,NaN,13.0,Croatia
498,https://www.imdb.com/title/tt28349451/,The Shadow Strays,"['Action', 'Crime', 'Thriller']","Codename 13, a 17-year-old assassin, is suspen...","['Aurora Ribero', 'Hana Malasan', 'Taskya Namy...","['Indonesian', 'English', 'Japanese', 'Chinese']","Codename 13, a 17-year-old trained assassin is...","['Frontier Pictures', 'XYZ Films']",2024-10-17,Not_Found,6.5,8600.0,0.0,NaN,144.0,United States
499,https://www.imdb.com/title/tt31609000/,Anthracite,"['Crime', 'Drama', 'Mystery', 'Thriller']",An old case is wrenched open when a reporter g...,"['Hatik', 'Noémie Schmidt', 'Camille Lou', 'Ni...",['French'],"In 1994, the collective suicide of a sect base...",['Mediawan'],2024-04-10,Not_Found,6.1,4800.0,0.0,NaN,50.0,United States
500,https://www.imdb.com/title/tt14203572/,Monsieur Spade,"['Crime', 'Drama', 'Thriller']",The famous detective Sam Spade is now 60 and l...,"['Clive Owen', 'Cara Bossom', 'Denis Ménochet'...","['English', 'French']",Monsieur Spade centers around the infamous pro...,"['Black Bear', 'Haut Et Court Tv']",2024-01-14,Not_Found,6.8,7400.0,0.0,NaN,NaN,United States

In [131]:
df["Cast"] = df["Cast"].astype(str).str.strip("[]").str.replace("'", "")
df["Cast"] = df["Cast"].apply(lambda x: x.split(", ") if x != "nan" else [])
df_exploded = df.explode("Cast")

In [132]:
df_exploded

,Home_Page,Movie_Name,Genres,Overview,Cast,Original_Language,Storyline,Production_Company,Release_Date,Tagline,Vote_Average,Vote_Count,Budget_USD,Revenue_$,Run_Time_Minutes,Release_Country
0,https://www.imdb.com/title/tt5040012/,Nosferatu,"['Fantasy', 'Horror', 'Mystery']",A gothic tale of obsession between a haunted y...,Lily-Rose Depp,"['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,"['Focus Features', 'Maiden Voyage Pictures', '...",2024-12-25,Succumb to the darkness.,7.3,151000.0,50000000.0,176000000.0,132.0,United States
0,https://www.imdb.com/title/tt5040012/,Nosferatu,"['Fantasy', 'Horror', 'Mystery']",A gothic tale of obsession between a haunted y...,Nicholas Hoult,"['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,"['Focus Features', 'Maiden Voyage Pictures', '...",2024-12-25,Succumb to the darkness.,7.3,151000.0,50000000.0,176000000.0,132.0,United States
0,https://www.imdb.com/title/tt5040012/,Nosferatu,"['Fantasy', 'Horror', 'Mystery']",A gothic tale of obsession between a haunted y...,Bill Skarsgård,"['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,"['Focus Features', 'Maiden Voyage Pictures', '...",2024-12-25,Succumb to the darkness.,7.3,151000.0,50000000.0,176000000.0,132.0,United States
0,https://www.imdb.com/title/tt5040012/,Nosferatu,"['Fantasy', 'Horror', 'Mystery']",A gothic tale of obsession between a haunted y...,Aaron Taylor-Johnson,"['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,"['Focus Features', 'Maiden Voyage Pictures', '...",2024-12-25,Succumb to the darkness.,7.3,151000.0,50000000.0,176000000.0,132.0,United States
0,https://www.imdb.com/title/tt5040012/,Nosferatu,"['Fantasy', 'Horror', 'Mystery']",A gothic tale of obsession between a haunted y...,Willem Dafoe,"['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,"['Focus Features', 'Maiden Voyage Pictures', '...",2024-12-25,Succumb to the darkness.,7.3,151000.0,50000000.0,176000000.0,132.0,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,https://www.imdb.com/title/tt14203572/,Monsieur Spade,"['Crime', 'Drama', 'Thriller']",The famous detective Sam Spade is now 60 and l...,Ismaël Berqouch,"['English', 'French']",Monsieur Spade centers around the infamous pro...,"['Black Bear', 'Haut Et Court Tv']",2024-01-14,Not_Found,6.8,7400.0,0.0,NaN,NaN,United States
500,https://www.imdb.com/title/tt14203572/,Monsieur Spade,"['Crime', 'Drama', 'Thriller']",The famous detective Sam Spade is now 60 and l...,Vincent Nemeth,"['English', 'French']",Monsieur Spade centers around the infamous pro...,"['Black Bear', 'Haut Et Court Tv']",2024-01-14,Not_Found,6.8,7400.0,0.0,NaN,NaN,United States
500,https://www.imdb.com/title/tt14203572/,Monsieur Spade,"['Crime', 'Drama', 'Thriller']",The famous detective Sam Spade is now 60 and l...,Inès Melab,"['English', 'French']",Monsieur Spade centers around the infamous pro...,"['Black Bear', 'Haut Et Court Tv']",2024-01-14,Not_Found,6.8,7400.0,0.0,NaN,NaN,United States
500,https://www.imdb.com/title/tt14203572/,Monsieur Spade,"['Crime', 'Drama', 'Thriller']",The famous detective Sam Spade is now 60 and l...,Roméo De Lacour,"['English', 'French']",Monsieur Spade centers around the infamous pro...,"['Black Bear', 'Haut Et Court Tv']",2024-01-14,Not_Found,6.8,7400.0,0.0,NaN,NaN,United States
500,https://www.imdb.com/title/tt14203572/,Monsieur Spade,"['Crime', 'Drama', 'Thriller']",The famous detective Sam Spade is now 60 and l...,Eric Colonge,"['English', 'French']",Monsieur Spade centers around the infamous pro...,"['Black Bear', 'Haut Et Court Tv']",2024-01-14,Not_Found,6.8,7400.0,0.0,NaN,NaN,United States

In [133]:
# Группируем по стране и актёру, суммируем голоса
actor_popularity = df_exploded.groupby(["Release_Country", "Cast"])["Vote_Count"].sum().reset_index()
actor_popularity

     Release_Country               Cast  Vote_Count
0              Aruba      Austin Butler       426.0
1              Aruba      Cody Robinson       426.0
2              Aruba      David Brinson       426.0
3              Aruba          David Gow       426.0
4              Aruba        Eric Skiles       426.0
...              ...                ...         ...
7865         Vietnam  Leon Nurse-Joseph      2600.0
7866         Vietnam  Milan Walls-Smith      2600.0
7867         Vietnam        Naomi Scott      2600.0
7868         Vietnam     Paisley Roemer      2600.0
7869         Vietnam     Zachary Quinto      2600.0

[7870 rows x 3 columns]

In [134]:
# Определяем самого популярного актёра в каждой стране
top_actors_by_country = actor_popularity.loc[actor_popularity.groupby("Release_Country")["Vote_Count"].idxmax()]
top_actors_by_country.sort_values(by = 'Vote_Count', ascending= False)

     Release_Country                         Cast  Vote_Count
5175   United States                Leslie Uggams    761000.0
616            India                Fahadh Faasil     77000.0
1218  United Kingdom                "Katy OBrian"     54000.0
148           Canada                 Chika Ikogwe     49000.0
1056     South Korea              Baek Seung-chul     22000.0
1094           Spain            Alessandro Nivola     16000.0
830            Italy  Amir Antonio Samande Chavez     15000.0
882            Japan                 Ayane Sakura     12000.0
12         Australia                  Adam Elliot     11000.0
290          Estonia                Eero Milonoff      9300.0
250            China                   Aaron Kwok      8100.0
313           France                   Anand Sami      7300.0
418          Germany             Ali Asghar Nejat      6200.0
82           Austria                  Agnes Lampl      5400.0
506          Iceland                Akshay Khanna      4900.0
488          Hungary                 Andrew Leeds      4400.0
95           Belgium              Cassie Alcendor      4100.0
984           Norway                   Basel Adra      3700.0
1002     Philippines                  Ahmad Sakhi      2800.0
113           Brazil               Austin Stowell      2600.0
7862         Vietnam                Anthony Ramos      2600.0
962      Netherlands                   Shiori Itô      2100.0
914        Lithuania         Algirdas Dainavicius      1900.0
1182          Turkey        Abdurrahman Yunusoglu      1700.0
281          Denmark               "Naomi OGarro"      1400.0
268          Croatia               Alexis Manenti      1300.0
470        Hong Kong                     Adam Pak      1100.0
1146          Sweden               Albin Grenholm       772.0
800          Ireland              Aaron Heffernan       743.0
0              Aruba                Austin Butler       426.0
1038          Russia              Aleksandr Prost       380.0
965      New Zealand                Angus Stevens       219.0
1020          Poland                 Alec Baldwin       113.0

In [135]:
fig1 = px.scatter_geo(top_actors_by_country,
                      locations="Release_Country",
                      locationmode="country names",
                      size="Vote_Count",
                      hover_name="Cast",
                      color="Cast",  # Добавляем цветовую дифференциацию по актёрам
                      title="Самые популярные актёры по странам",
                      projection="natural earth")

fig1.show()

In [136]:
country_movie_count = df["Release_Country"].value_counts().reset_index()
country_movie_count.columns = ["Release_Country", "Movie_Count"]
country_movie_count

   Release_Country  Movie_Count
0    United States          414
1            India           16
2   United Kingdom           11
3           Canada            7
4           France            6
5        Australia            4
6            Italy            3
7            Spain            3
8          Germany            3
9      Netherlands            3
10          Norway            2
11         Ireland            2
12     South Korea            2
13           Japan            2
14          Turkey            2
15         Iceland            2
16          Sweden            2
17          Brazil            2
18     New Zealand            1
19       Lithuania            1
20         Austria            1
21          Russia            1
22          Poland            1
23       Hong Kong            1
24         Denmark            1
25     Philippines            1
26         Belgium            1
27           Aruba            1
28         Estonia            1
29           China            1
30         Hungary            1
31         Vietnam            1
32         Croatia            1

In [137]:
fig3 = px.choropleth(country_movie_count,
                      locations="Release_Country",
                      locationmode="country names",
                      color="Release_Country",  # Используем страну для цвета
                      title="Количество проектов, выпущенных в каждой стране",
                      projection="natural earth",
                      color_discrete_sequence=px.colors.qualitative.Set3,  # Уникальная палитра
                      hover_name="Release_Country",  # Показываем название страны при наведении
                      hover_data={"Release_Country": False, "Movie_Count": True})  # Показываем количество фильмов

fig3.show()

In [138]:
df["Info"] = df.apply(lambda row: 
    f"Название: {row['Movie_Name']}<br>"
    f"Дата выхода: {row['Release_Date']}<br>"
    f"Бюджет: ${row['Budget_USD']:,.0f}<br>"
    f"Оценка: {row['Vote_Average']}", axis=1)

In [139]:
df

,Home_Page,Movie_Name,Genres,Overview,Cast,Original_Language,Storyline,Production_Company,Release_Date,Tagline,Vote_Average,Vote_Count,Budget_USD,Revenue_$,Run_Time_Minutes,Release_Country,Info
0,https://www.imdb.com/title/tt5040012/,Nosferatu,"['Fantasy', 'Horror', 'Mystery']",A gothic tale of obsession between a haunted y...,"[Lily-Rose Depp, Nicholas Hoult, Bill Skarsgår...","['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,"['Focus Features', 'Maiden Voyage Pictures', '...",2024-12-25,Succumb to the darkness.,7.3,151000.0,50000000.0,176000000.0,132.0,United States,Название: Nosferatu<br>Дата выхода: 2024-12-25...
1,https://www.imdb.com/title/tt20221436/,Emilia Pérez,"['Comedy', 'Crime', 'Drama', 'Musical', 'Thril...",Emilia Pérez follows three remarkable women in...,"[Zoe Saldaña, Karla Sofía Gascón, Selena Gomez...","['Spanish', 'English']","In modern-day Mexico, overqualified and exploi...","['Why Not Productions', 'Page 114', 'Pathé']",2024-11-13,Not_Found,5.5,71000.0,27300000.0,15000000.0,132.0,United States,Название: Emilia Pérez<br>Дата выхода: 2024-11...
2,https://www.imdb.com/title/tt8999762/,The Brutalist,['Drama'],When a visionary architect and his wife flee p...,"[Adrien Brody, Felicity Jones, Guy Pearce, Joe...","['English', 'Hungarian', 'Italian', 'Hebrew', ...",When visionary architect László Toth and his w...,"['Brookstreet Pictures', 'Kaplan Morrison', 'I...",2025-01-24,Welcome to America.,7.9,28000.0,10000000.0,31100000.0,214.0,Canada,Название: The Brutalist<br>Дата выхода: 2025-0...
3,https://www.imdb.com/title/tt27657135/,Saturday Night,"['Biography', 'Comedy', 'Drama', 'History']","At 11:30pm on October 11th, 1975, a ferocious ...","[Gabriel LaBelle, Rachel Sennott, Cory Michael...",['English'],"At 11:30pm on October 11, 1975, a ferocious tr...","['Columbia Pictures', 'TSG Entertainment']",2024-10-11,"October 11, 1975, The First Saturday Night Liv...",7.0,26000.0,25000000.0,10000000.0,109.0,United States,Название: Saturday Night<br>Дата выхода: 2024-...
4,https://www.imdb.com/title/tt17526714/,The Substance,"['Drama', 'Horror', 'Sci-Fi']",A fading celebrity takes a black-market drug: ...,"[Demi Moore, Margaret Qualley, Dennis Quaid, E...",['English'],Have you ever dreamed of a better version of y...,"['Working Title Films', 'A Good Story', 'Black...",2024-09-20,"If you follow the instructions, what could go ...",7.3,249000.0,17500000.0,77000000.0,141.0,United States,Название: The Substance<br>Дата выхода: 2024-0...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,https://www.imdb.com/title/tt28288478/,The Cage,"['Biography', 'Drama', 'Sport']","Dreaming of going pro, a young fighter struggl...","[Franck Gastambide, Melvin Boomer, Bosh, Camil...",['French'],"Dreaming of going pro, a young fighter struggl...",['Ondamax Films'],2024-11-08,Fight for your dreams.,6.5,2300.0,0.0,NaN,45.0,United States,Название: The Cage<br>Дата выхода: 2024-11-08<...
497,https://www.imdb.com/title/tt20519854/,The Man Who Could Not Remain Silent,"['Short', 'Drama']","1993, Bosnia and Herzegovina. A passenger trai...","[Dragan Micanovic, Goran Bogdan, Alexis Manent...",['Croatian'],"1993, Bosnia and Herzegovina. A passenger trai...","['Antitalent Produkcija', 'Contrast Films', 'L...",2025-01-16,Not_Found,7.4,1300.0,0.0,NaN,13.0,Croatia,Название: The Man Who Could Not Remain Silent<...
498,https://www.imdb.com/title/tt28349451/,The Shadow Strays,"['Action', 'Crime', 'Thriller']","Codename 13, a 17-year-old assassin, is suspen...","[Aurora Ribero, Hana Malasan, Taskya Namya, Ag...","['Indonesian', 'English', 'Japanese', 'Chinese']","Codename 13, a 17-year-old trained assassin is...","['Frontier Pictures', 'XYZ Films']",2024-10-17,Not_Found,6.5,8600.0,0.0,NaN,144.0,United States,Название: The Shadow Strays<br>Дата выхода: 20...
499,https://www.imdb.com/title/tt31609000/,Anthracite,"['Crime', 'Drama', 'Mystery', 'Thriller']",An old case is wrenched open when a reporter g...,"[Hatik, Noémie Schmidt, Camille Lou, Nicolas G...",['French'],"In 1994, the collective suicide of a sect base...",['Mediawan'],2024-04-10,Not_Found,6.1,4800.0,0.0,NaN,50.0,United States,Название: Anthracite<br>Дата выхода: 2024-04-1...
500,https://www.imdb.com/title/tt14203572/,Monsieur Spade,"['Crime', 'Drama', 'Thriller']",The famous detective Sam Spade is now 60 and l...,"[Clive Owen, Cara Bossom, Denis Ménochet, Loui...","['English', 'French']",Monsieur Spade centers around the infamous pro...,"['Black Bear', 'Haut Et Court Tv']",2024-01-14,Not_Found,6.8,7400.0,0.0,NaN,NaN,United States,Название: Monsieur Spade<br>Дата выхода: 2024-...

In [140]:
top_movies_by_country = df.sort_values("Vote_Count", ascending=False).drop_duplicates("Release_Country")
top_movies_by_country

,Home_Page,Movie_Name,Genres,Overview,Cast,Original_Language,Storyline,Production_Company,Release_Date,Tagline,Vote_Average,Vote_Count,Budget_USD,Revenue_$,Run_Time_Minutes,Release_Country,Info
40,https://www.imdb.com/title/tt15239678/,Dune: Part Two,"['Action', 'Adventure', 'Drama', 'Sci-Fi']",Paul Atreides unites with the Fremen while on ...,"[Timothée Chalamet, Zendaya, Rebecca Ferguson,...",['English'],Paul Atreides unites with Chani and the Fremen...,"['Warner Bros.', 'Legendary Entertainment', 'V...",2024-03-01,Long live the fighters.,8.5,599000.0,190000000.0,714600000.0,166.0,United States,Название: Dune: Part Two<br>Дата выхода: 2024-...
149,https://www.imdb.com/title/tt19637052/,Love Lies Bleeding,"['Action', 'Adventure', 'Crime', 'Mystery', 'R...",Reclusive gym manager Lou falls hard for Jacki...,"[Anna Baryshnikov, Kristen Stewart, Dave Franc...",['English'],From Director Rose Glass comes an electric new...,"['A24', 'Film4', 'Escape Plan Productions']",2024-05-03,Revenge gets ripped.,6.6,54000.0,0.0,12800000.0,104.0,United Kingdom,Название: Love Lies Bleeding<br>Дата выхода: 2...
387,https://www.imdb.com/title/tt13818368/,Fighter,"['Action', 'Drama']",A reckless yet brilliant squadron leader and h...,"[Hrithik Roshan, Deepika Padukone, Anil Kapoor...","['Hindi', 'English']",Group Captain Rakesh Jai Singh (Rocky) is assi...,"['Betterfly Films', 'Manomay Motion Pictures',...",2024-01-25,Not_Found,6.2,52000.0,3000000.0,3800000.0,166.0,India,Название: Fighter<br>Дата выхода: 2024-01-25<b...
214,https://www.imdb.com/title/tt19864802/,Land of Bad,"['Action', 'Thriller']",A Delta Force team fights for survival as an A...,"[Liam Hemsworth, Russell Crowe, Luke Hemsworth...",['English'],A Delta Force team fights for survival as an A...,"['Volition Media Partners', 'Broken Open Pictu...",2024-02-16,No man left behind.,6.6,49000.0,16500000.0,7000000.0,113.0,Canada,Название: Land of Bad<br>Дата выхода: 2024-02-...
289,https://www.imdb.com/title/tt27802490/,Exhuma,"['Drama', 'Horror', 'Mystery', 'Thriller']",The process of excavating an ominous grave unl...,"[Kim Go-eun, Choi Min-sik, Lee Do-hyun, Kim Su...","['Korean', 'English', 'Japanese']",The process of excavating an ominous grave unl...,['Showbox Entertainment'],2024-02-22,The Vicious Emerges,6.9,22000.0,0.0,93900000.0,134.0,South Korea,Название: Exhuma<br>Дата выхода: 2024-02-22<br...
86,https://www.imdb.com/title/tt29439114/,The Room Next Door,['Drama'],Ingrid and Martha were close friends in their ...,"[Julianne Moore, Tilda Swinton, John Turturro,...",['English'],Ingrid (Julianne Moore) and Martha (Tilda Swin...,"['Crea SGR', 'El Deseo', 'Instituto de Crédito...",2024-10-18,Not_Found,6.9,16000.0,0.0,16100000.0,107.0,Spain,Название: The Room Next Door<br>Дата выхода: 2...
59,https://www.imdb.com/title/tt24176060/,Queer,"['Biography', 'Drama', 'History', 'Romance']","In 1950s Mexico City, an American immigrant in...","[Daniel Craig, Daan de Wit, Jason Schwartzman,...","['English', 'Spanish', 'French']","William Lee, an American expat and heroin addi...","['The Apartment', 'Frenesy Film Company', 'Fre...",2025-04-17,Not_Found,6.5,15000.0,0.0,4900000.0,137.0,Italy,Название: Queer<br>Дата выхода: 2025-04-17<br>...
368,https://www.imdb.com/title/tt33175825/,Attack on Titan the Movie: The Last Attack,"['Animation', 'Action', 'Drama']",The fate of the world hangs in the balance as ...,"[Natsuki Hanae, Yoshimasa Hosoya, Marina Inoue...",['Japanese'],The fate of the world hangs in the balance as ...,['Mappa'],2024-11-08,Not_Found,9.3,12000.0,0.0,11400000.0,145.0,Japan,Название: Attack on Titan the Movie: The Last ...
159,https://www.imdb.com/title/tt23770030/,Memoir of a Snail,"['Animation', 'Drama']",A bittersweet memoir of a melancholic woman ca...,"[Jacki Weaver, Sarah Snook, Charlotte Belsey, ...","['English', 'French']",A bittersweet memoir of a melancholic woman ca...,"['Arenamedia', 'Screen Australia', 'Snails Pac...",2024-10-17,"Life can only be understood backwards, but we ...",7.8,11000.0,0.0,1900000.0,95.0,Australia,Название: Memoir of a Snail<br>Дата выхода: 20...
197,https://www.imdb.com/title/tt22173666/,Azrael,"['Action', 'Horror']","In a world where no one speaks, a devout femal...","[Vic Carmen Sonne, Samara Weaving, Nathan Stew...","['None', 'Esperanto']","Many years following the apocalypse, a devout ...","['C2 Motion Picture Group', 'Homeless Bob Prod...",2024-09-27,After The Rapture Those Left On Earth Will Suf...,5.4,9300.0,12000000.0,666600.0,86.0,Estonia,Название: Azrael<br>Дата выхода: 2024-09-27<br...
192,https://www.imdb.com/title/tt20316748/,Twilight of the Warriors: Walled In,"['Action', 'Crime', 'Thriller']",Follows troubled youth Chan Lok-kwun as he acc...,"[Louis Koo, Sammo Kam-Bo Hung, Richie Jen, Ray...","['Cantonese', 'Mandarin']",Follows troubled youth Chan Lok-kwun as he acc...,"['Entertaining Power', 'HG Entertainment Film ...",2024-05-01,Don't cause trouble in the walled city,7.0,8100.0,39000000.0,17100000.0,126.0,China,Название: Twilight of the Warriors: Walled In<...
166,https://www.imdb.com/title/tt32086077/,All We Imagine as Light,"['Drama', 'Romance']","In Mumbai, Nurse Prabha's routine is troubled ...","[Kani Kusruti, Divya Prabha, Chhaya Kadam, Hri...","['Malayalam', 'Hindi', 'Marathi', 'English', '...","In Mumbai, Nurse Prabha's routine is troubled ...","['Petit Chaos', 'Chalk and Cheese Films', 'BAL...",2024-10-02,When you try to imagine light you cannot,7.1,7300.0,0.0,3100000.0,118.0,France,Название: All We Imagine as Light<br>Дата выхо...
445,https://www.imdb.com/title/tt31015278/,My Favourite Cake,['Not_Found'],"Seventy-year-old Mahin, solitary until now, ch...","[Lili Farhadpour, Esmaeel Mehrabi, Mansoore Il...",['Persian'],Not_Found,"['Caracteres Productions', 'Filmsazane Javan',...",2024-07-11,Not_Found,7.4,6200.0,0.0,1700000.0,97.0,Germany,Название: My Favourite Cake<br>Дата выхода: 20...
417,https://www.imdb.com/title/tt29141112/,The Devil's Bath,['Not_Found'],Austria in the 18th century. Forests surround ...,"[Anja Plaschg, Maria Hofstätter, David Scheid,...",['German'],Not_Found,"['Ulrich Seidl Film Produktion GmbH', 'Heimfil...",2024-03-08,Not_Found,6.6,5400.0,0.0,54300.0,121.0,Austria,Название: The Devil's Bath<br>Дата выхода: 202...
337,https://www.imdb.com/title/tt23468836/,Touch,"['Drama', 'Romance']",A romantic and thrilling story that spans seve...,"[Egill Ólafsson, Kôki, Palmi Kormákur, Masahir...","['English', 'Japanese', 'Icelandic']",A romantic and thrilling story that spans seve...,"['RVK Studios', 'Good Chaos']",2024-05-29,Discover what might have been.,7.4,4900.0,0.0,3000000.0,121.0,Iceland,Название: Touch<br>Дата выхода: 2024-05-29<br>...
191,https://www.imdb.com/title/tt10171472/,Goodrich,"['Comedy', 'Drama']",Andy Goodrich's life is upended when his wife ...,"[Michael Keaton, Mila Kunis, Danny Deferrari, ...",['English'],Andy Goodrich's (Michael Keaton) life is upend...,"['C2 Motion Picture Group', 'CaliWood Pictures...",2024-10-17,"If life isn't kicking your ass, it's not doing...",6.3,4400.0,0.0,2000000.0,110.0,Hungary,Название: Goodrich<br>Дата выхода: 2024-10-17<...
274,https://www.imdb.com/title/tt15245268/,Young Hearts,"['Drama', 'Family']",Elias develops feelings for his new neighbor A...,"[Lou Goossens, Marius De Saeger, Geert Van Ram...","['Dutch', 'French']",Elias (14) feels attracted to his new neighbou...,"['Kwassa Films', 'Polar Bear']",2024-12-18,Not_Found,8.2,4100.0,0.0,NaN,97.0,Belgium,Название: Young Hearts<br>Дата выхода: 2024-12...
219,https://www.imdb.com/title/tt30953759/,No Other Land,['Documentary'],This film made by a Palestinian-Israeli collec...,"[Yuval Abraham, Basel Adra, Hamdan Ballal]","['Arabic', 'English', 'Hebrew']",This film made by a Palestinian-Israeli collec...,"['Yabayay Media', 'Antipode Films']",2025-02-07,Not_Found,8.3,3700.0,0.0,402200.0,92.0,Norway,Название: No Other Land<br>Дата выхода: 2025-0...
305,https://www.imdb.com/title/tt23872640/,Dirty Angels,"['Action', 'Drama', 'Thriller', 'War']",It centers on a group of female soldiers who d...,"[Eva Green, Maria Bakalova, Ruby Rose, Reza Br...",['English'],It centers on a group of female soldiers who d...,"['I Road Productions', 'Millennium Media', 'Nu...",2024-12-11,Fight Your Way Out.,4.3,2800.0,0.0,27200.0,104.0,Philippines,Название: Dirty Angels<br>Дата выхода: 2024-12...
175,https://www.imdb.com/title/tt9883398/,Distant,"['Comedy', 'Drama', 'Sci-Fi', 'Thriller']","It follows an asteroid miner who, after crash-...","[Anthony Ramos, Naomi Scott, Kristofer Hivju, ...",['English'],"It follows an asteroid miner who, after crash-...","['Amblin Partners', 'Amblin Entertainment', 'A...",2024-07-12,Not_Found,5.7,2600.0,0.0,NaN,87.0,Vietnam,Название: Distant<br>Дата выхода: 2024-07-12<b...
341,https://www.imdb.com/title/tt9271850/,The Inheritance,"['Horror', 'Thriller']","A billionaire on the eve of his 75th birthday,...","[Bob Gunton, Peyton List, Briana Middleton, Ra...",['English'],"A billionaire on the eve of his 75th birthday,...",['Paul Schiff Productions'],2024-07-12,Not_Found,4.7,2600.0,14000000.0,NaN,85.0,Brazil,Название: The Inheritance<br>Дата выхода: 2024...
323,https://www.imdb.com/title/tt30227076/,Black Box Diaries,['Documentary'],Journalist Shiori Ito investigates her own sex...,[Shiori Itô],"['English', 'Japanese']",Journalist Shiori Ito investigates her own sex...,"['Cineric Creative', 'Hanashi Films', 'Spark F...",2024-11-28,Not_Found,7.5,2100.0,0.0,32800.0,102.0,Netherlands,Название: Black Box Diaries<br>Дата выхода: 20...
406,https://www.imdb.com/title/tt14064760/,The Southern Chronicles,['Not_Found'],It follows Rimants who is more interested in p...,"[Dziugas Grinys, Robertas Petraitis, Digna Kul...",['Lithuanian'],Not_Found,"['LRT', 'iN SCRiPT']",2025-01-24,Not_Found,8.9,1900.0,0.0,1700000.0,120.0,Lithuania,Название: The Southern Chronicles<br>Дата выхо...
490,https://www.imdb.com/title/tt31869878/,Genius,['Drama'],"Devran, a prodigious young mathematician, navi...","[Aras Bulut Iynemli, Ugur Polat, Taner Ölmez, ...",['Turkish'],"Devran, a prodigious young mathematician, navi...",['Ay Yapim'],2024-09-22,Not_Found,7.6,1700.0,0.0,NaN,NaN,Turkey,Название: Genius<br>Дата выхода: 2024-09-22<br...
335,https://www.imdb.com/title/tt15551346/,The End,"['Drama', 'Fantasy', 'Musical', 'Sci-Fi']","After decades alone, a wealthy family living i...","[Tilda Swinton, George MacKay, Moses Ingram, M...",['English'],A post-apocalyptic story about a rich family l...,"['Final Cut for Real', 'The Match Factory', 'W...",2025-02-20,Not_Found,5.5,1400.0,0.0,141700.0,148.0,Denmark,Название: The End<br>Дата выхода: 2025-02-20<b...
497,https://www.imdb.com/title/tt20519854/,The Man Who Could Not Remain Silent,"['Short', 'Drama']","1993, Bosnia and Herzegovina. A passenger trai...","[Dragan Micanovic, Goran Bogdan, Alexis Manent...",['Croatian'],"1993, Bosnia and Herzegovina. A passenger trai...","['Antitalent Produkcija', 'Contrast Films', 'L...",2025-01-16,Not_Found,7.4,1300.0,0.0,NaN,13.0,Croatia,Название: The Man Who Could Not Remain Silent<...
265,https://www.imdb.com/title/tt30024043/,The Prosecutor,"['Action', 'Thriller']",A poor young man is wrongly charged with drug ...,"[Donnie Yen, Julian Cheung, Francis Ng, Kent C...",['Cantonese'],"A young man is charged with drug trafficking, ...","['Huace Pictures', 'Mandarin Motion Pictures',...",2024-12-21,Fight for justice.,6.9,1100.0,40300000.0,4000000.0,117.0,Hong Kong,Название: The Prosecutor<br>Дата выхода: 2024-...
414,https://www.imdb.com/title/tt27627059/,Cry Wolf,['Not_Found'],"When human remains are found in a dead wolf, p...","[Eva Melander, Eliot Sumner, Henrik Dorsin, Am...",['Swedish'],Not_Found,"['Nordic Drama Queens', 'UAB Ahil']",2024-12-25,Not_Found,5.8,772.0,0.0,NaN,45.0,Sweden,Название: Cry Wolf<br>Дата выхода: 2024-12-25<...
331,https://www.imdb.com/title/tt14186876/,Bring Them Down,"['Drama', 'Thriller']",An Irish shepherding family thrust into battle...,"[Christopher Abbott, Barry Keoghan, Colm Meane...","['English', 'Irish Gaelic']","Michael, the last son of a shepherding family,...","['MUBI', 'Tailored Films', 'Wild Swim Films']",2025-02-07,Not_Found,6.8,743.0,0.0,422800.0,106.0,Ireland,Название: Bring Them Down<br>Дата выхода: 2025...
254,https://www.imdb.com/title/tt32117345/,The Intruder,['Thriller'],"A young, paranoid man begins to believe someon...","[David Gow, Steve McNair, Monica Bell, Cody Ro...",['English'],"A young, paranoid man begins to believe someon...",['Not_Found'],2025-01-30,Not_Found,4.8,426.0,10000.0,NaN,101.0,Aruba,Название: The Intruder<br>Дата выхода: 2025-01...
344,https://www.imdb.com/title/tt30225465/,Why Do You?,"['Drama', 'Romance', 'Thriller']","Love comes without asking. Often not to those,...","[Daniil Vorobyov, Angelina Zagrebina, Aleksand...",['Russian'],"Love comes without asking. Often not to those,...",['Andreevskaya 5'],2024-04-25,Not_Found,5.4,380.0,0.0,291600.0,103.0,Russia,Название: Why Do You?<br>Дата выхода: 2024-04-...
351,https://www.imdb.com/title/tt29338758/,Madam,['Comedy'],"Mack Leigh, faced with a philandering husband ...","[Rachel Griffiths, Ariana Osborne, Carmel McGl...",['English'],"Mack Leigh, faced with a philandering husband ...","['IPR.VC', 'Tavake', 'Te Puna Kairangi']",2024-07-04,Not_Found,6.4,219.0,0.0,NaN,NaN,New Zealand,Название: Madam<br>Дата выхода: 2024-07-04<br>...
495,https://www.imdb.com/title/tt11001074/,Rust,['Western'],A boy left to fend for himself and his younger...,"[Travis Fimmel, Frances Fisher, Alec Baldwin, ...",['English'],A 13-year-old boy left to fend for himself and...,"['BondIt Media Capital', 'Cavalry Media', 'El ...",2024-11-20,Not_Found,4.1,113.0,7000000.0,NaN,NaN,Poland,Название: Rust<br>Дата выхода: 2024-11-20<br>Б...

In [141]:
fig4 = px.choropleth(top_movies_by_country,
                     locations="Release_Country",  # Столбец с названиями стран
                     locationmode="country names",  # Режим отображения стран
                     hover_name="Release_Country",  # Название страны при наведении
                     hover_data={"Info": True},  # Отображаем всю информацию
                     color="Vote_Count",  # Цветовая гамма зависит от количества голосов
                     color_continuous_scale=px.colors.sequential.Plasma,  # Цветовая шкала
                     title="Популярные фильмы/сериалы по странам",  # Заголовок
                     projection="natural earth")  # Проекция карты
fig4.show()

In [142]:
fig4.update_traces(hovertemplate="%{customdata[0]}")  # Формат всплывающей информации
fig4.update_layout(coloraxis_colorbar=dict(title="Количество голосов"))  # Название цветовой шкалы
fig4.show()

In [143]:
fig = px.box(df, x="Release_Country", y="Vote_Average", 
             title="Распределение рейтингов фильмов/сериалов по странам",
             labels={"Release_Country": "Страна выпуска", "Vote_Average": "Рейтинг"},
             points="all")  # Отображение всех точек

# Отображение графика
fig.show()

In [144]:
# Создание боксплота с названиями фильмов и бюджетом в подсказках
fig = px.box(df, x="Release_Country", y="Vote_Average", 
             title="Распределение рейтингов фильмов/сериалов по странам",
             labels={"Release_Country": "Страна выпуска", "Vote_Average": "Рейтинг"},
             hover_data=["Movie_Name", "Budget_USD"],  # Добавляем названия фильмов и бюджет
             points="all")  # Отображение всех точек

# Отображение графика
fig.show()

In [145]:
country_avg_rating = df.groupby("Release_Country")["Vote_Average"].mean().reset_index()
country_avg_rating

   Release_Country  Vote_Average
0            Aruba      4.800000
1        Australia      6.850000
2          Austria      6.600000
3          Belgium      8.200000
4           Brazil      5.200000
5           Canada      6.600000
6            China      7.000000
7          Croatia      7.400000
8          Denmark      5.500000
9          Estonia      5.400000
10          France      5.933333
11         Germany      6.866667
12       Hong Kong      6.900000
13         Hungary      6.300000
14         Iceland      6.700000
15           India      7.000000
16         Ireland      6.900000
17           Italy      6.733333
18           Japan      8.800000
19       Lithuania      8.900000
20     Netherlands      6.500000
21     New Zealand      6.400000
22          Norway      7.250000
23     Philippines      4.300000
24          Poland      4.100000
25          Russia      5.400000
26     South Korea      7.450000
27           Spain      6.066667
28          Sweden      6.200000
29          Turkey      7.450000
30  United Kingdom      6.400000
31   United States      6.548792
32         Vietnam      5.700000

In [146]:

fig3 = px.choropleth(country_avg_rating,
                      locations="Release_Country",
                      locationmode="country names",
                      color="Vote_Average",
                      title="Средний рейтинг фильмов по странам",
                      projection="natural earth",
                      color_continuous_scale="Plasma")

fig3.show()

In [147]:
fig4 = px.histogram(df, x="Vote_Average", nbins=20, title="Распределение рейтингов фильмов", labels={"Vote_Average": "Рейтинг"})
fig4.show()

In [148]:
df["Genres"] = df["Genres"].astype(str).str.strip("[]").str.replace("'", "")
df["Genres"] = df["Genres"].apply(lambda x: x.split(", ") if x != "nan" else [])
df_genres = df.explode("Genres")
df_genres

,Home_Page,Movie_Name,Genres,Overview,Cast,Original_Language,Storyline,Production_Company,Release_Date,Tagline,Vote_Average,Vote_Count,Budget_USD,Revenue_$,Run_Time_Minutes,Release_Country,Info
0,https://www.imdb.com/title/tt5040012/,Nosferatu,Fantasy,A gothic tale of obsession between a haunted y...,"[Lily-Rose Depp, Nicholas Hoult, Bill Skarsgår...","['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,"['Focus Features', 'Maiden Voyage Pictures', '...",2024-12-25,Succumb to the darkness.,7.3,151000.0,50000000.0,176000000.0,132.0,United States,Название: Nosferatu<br>Дата выхода: 2024-12-25...
0,https://www.imdb.com/title/tt5040012/,Nosferatu,Horror,A gothic tale of obsession between a haunted y...,"[Lily-Rose Depp, Nicholas Hoult, Bill Skarsgår...","['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,"['Focus Features', 'Maiden Voyage Pictures', '...",2024-12-25,Succumb to the darkness.,7.3,151000.0,50000000.0,176000000.0,132.0,United States,Название: Nosferatu<br>Дата выхода: 2024-12-25...
0,https://www.imdb.com/title/tt5040012/,Nosferatu,Mystery,A gothic tale of obsession between a haunted y...,"[Lily-Rose Depp, Nicholas Hoult, Bill Skarsgår...","['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,"['Focus Features', 'Maiden Voyage Pictures', '...",2024-12-25,Succumb to the darkness.,7.3,151000.0,50000000.0,176000000.0,132.0,United States,Название: Nosferatu<br>Дата выхода: 2024-12-25...
1,https://www.imdb.com/title/tt20221436/,Emilia Pérez,Comedy,Emilia Pérez follows three remarkable women in...,"[Zoe Saldaña, Karla Sofía Gascón, Selena Gomez...","['Spanish', 'English']","In modern-day Mexico, overqualified and exploi...","['Why Not Productions', 'Page 114', 'Pathé']",2024-11-13,Not_Found,5.5,71000.0,27300000.0,15000000.0,132.0,United States,Название: Emilia Pérez<br>Дата выхода: 2024-11...
1,https://www.imdb.com/title/tt20221436/,Emilia Pérez,Crime,Emilia Pérez follows three remarkable women in...,"[Zoe Saldaña, Karla Sofía Gascón, Selena Gomez...","['Spanish', 'English']","In modern-day Mexico, overqualified and exploi...","['Why Not Productions', 'Page 114', 'Pathé']",2024-11-13,Not_Found,5.5,71000.0,27300000.0,15000000.0,132.0,United States,Название: Emilia Pérez<br>Дата выхода: 2024-11...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,https://www.imdb.com/title/tt31609000/,Anthracite,Mystery,An old case is wrenched open when a reporter g...,"[Hatik, Noémie Schmidt, Camille Lou, Nicolas G...",['French'],"In 1994, the collective suicide of a sect base...",['Mediawan'],2024-04-10,Not_Found,6.1,4800.0,0.0,NaN,50.0,United States,Название: Anthracite<br>Дата выхода: 2024-04-1...
499,https://www.imdb.com/title/tt31609000/,Anthracite,Thriller,An old case is wrenched open when a reporter g...,"[Hatik, Noémie Schmidt, Camille Lou, Nicolas G...",['French'],"In 1994, the collective suicide of a sect base...",['Mediawan'],2024-04-10,Not_Found,6.1,4800.0,0.0,NaN,50.0,United States,Название: Anthracite<br>Дата выхода: 2024-04-1...
500,https://www.imdb.com/title/tt14203572/,Monsieur Spade,Crime,The famous detective Sam Spade is now 60 and l...,"[Clive Owen, Cara Bossom, Denis Ménochet, Loui...","['English', 'French']",Monsieur Spade centers around the infamous pro...,"['Black Bear', 'Haut Et Court Tv']",2024-01-14,Not_Found,6.8,7400.0,0.0,NaN,NaN,United States,Название: Monsieur Spade<br>Дата выхода: 2024-...
500,https://www.imdb.com/title/tt14203572/,Monsieur Spade,Drama,The famous detective Sam Spade is now 60 and l...,"[Clive Owen, Cara Bossom, Denis Ménochet, Loui...","['English', 'French']",Monsieur Spade centers around the infamous pro...,"['Black Bear', 'Haut Et Court Tv']",2024-01-14,Not_Found,6.8,7400.0,0.0,NaN,NaN,United States,Название: Monsieur Spade<br>Дата выхода: 2024-...
500,https://www.imdb.com/title/tt14203572/,Monsieur Spade,Thriller,The famous detective Sam Spade is now 60 and l...,"[Clive Owen, Cara Bossom, Denis Ménochet, Loui...","['English', 'French']",Monsieur Spade centers around the infamous pro...,"['Black Bear', 'Haut Et Court Tv']",2024-01-14,Not_Found,6.8,7400.0,0.0,NaN,NaN,United States,Название: Monsieur Spade<br>Дата выхода: 2024-...

In [149]:
genre_count = df_genres["Genres"].value_counts().reset_index()
genre_count.columns = ["Genre", "Count"]
fig5 = px.bar(genre_count, x="Genre", y="Count", title="Количество фильмов по жанрам", labels={"Genre": "Жанр", "Count": "Количество фильмов"})
fig5.show()

In [150]:
top_actors = df_exploded.groupby("Cast")["Vote_Count"].sum().reset_index().sort_values(by="Vote_Count", ascending=False).head(10)
top_actors

                   Cast  Vote_Count
4444      Leslie Uggams    761000.0
7682            Zendaya    744000.0
917    Babs Olusanmokun    728000.0
2948       Henry Cavill    687000.0
874       Austin Butler    661426.0
2533      Florence Pugh    641000.0
7185  Timothée Chalamet    630000.0
2362        Emma Corrin    619000.0
1873      Dave Bautista    618100.0
3767        Josh Brolin    611000.0

In [151]:
fig6 = px.bar(top_actors, x="Cast", y="Vote_Count", title="Топ-10 актёров по популярности", labels={"Cast": "Актёр", "Vote_Count": "Суммарное количество голосов"}, text_auto=True)
fig6.show()

In [152]:
df = pd.read_csv('cleaned_imdb_2024.csv')
df

,Home_Page,Movie_Name,Genres,Overview,Cast,Original_Language,Storyline,Production_Company,Release_Date,Tagline,Vote_Average,Vote_Count,Budget_USD,Revenue_$,Run_Time_Minutes,Release_Country
0,https://www.imdb.com/title/tt5040012/,Nosferatu,"['Fantasy', 'Horror', 'Mystery']",A gothic tale of obsession between a haunted y...,"['Lily-Rose Depp', 'Nicholas Hoult', 'Bill Ska...","['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,"['Focus Features', 'Maiden Voyage Pictures', '...",2024-12-25,Succumb to the darkness.,7.3,151K,$50.0M,$176.0M,132,United States
1,https://www.imdb.com/title/tt20221436/,Emilia Pérez,"['Comedy', 'Crime', 'Drama', 'Musical', 'Thril...",Emilia Pérez follows three remarkable women in...,"['Zoe Saldaña', 'Karla Sofía Gascón', 'Selena ...","['Spanish', 'English']","In modern-day Mexico, overqualified and exploi...","['Why Not Productions', 'Page 114', 'Pathé']",2024-11-13,Not_Found,5.5,71K,$27.3M,$15.0M,132,United States
2,https://www.imdb.com/title/tt8999762/,The Brutalist,['Drama'],When a visionary architect and his wife flee p...,"['Adrien Brody', 'Felicity Jones', 'Guy Pearce...","['English', 'Hungarian', 'Italian', 'Hebrew', ...",When visionary architect László Toth and his w...,"['Brookstreet Pictures', 'Kaplan Morrison', 'I...",2025-01-24,Welcome to America.,7.9,28K,$10.0M,$31.1M,214,Canada
3,https://www.imdb.com/title/tt27657135/,Saturday Night,"['Biography', 'Comedy', 'Drama', 'History']","At 11:30pm on October 11th, 1975, a ferocious ...","['Gabriel LaBelle', 'Rachel Sennott', 'Cory Mi...",['English'],"At 11:30pm on October 11, 1975, a ferocious tr...","['Columbia Pictures', 'TSG Entertainment']",2024-10-11,"October 11, 1975, The First Saturday Night Liv...",7.0,26K,$25.0M,$10.0M,109,United States
4,https://www.imdb.com/title/tt17526714/,The Substance,"['Drama', 'Horror', 'Sci-Fi']",A fading celebrity takes a black-market drug: ...,"['Demi Moore', 'Margaret Qualley', 'Dennis Qua...",['English'],Have you ever dreamed of a better version of y...,"['Working Title Films', 'A Good Story', 'Black...",2024-09-20,"If you follow the instructions, what could go ...",7.3,249K,$17.5M,$77.0M,141,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,https://www.imdb.com/title/tt28288478/,The Cage,"['Biography', 'Drama', 'Sport']","Dreaming of going pro, a young fighter struggl...","['Franck Gastambide', 'Melvin Boomer', 'Bosh',...",['French'],"Dreaming of going pro, a young fighter struggl...",['Ondamax Films'],2024-11-08,Fight for your dreams.,6.5,2.3K,$0,$0,45,United States
497,https://www.imdb.com/title/tt20519854/,The Man Who Could Not Remain Silent,"['Short', 'Drama']","1993, Bosnia and Herzegovina. A passenger trai...","['Dragan Micanovic', 'Goran Bogdan', 'Alexis M...",['Croatian'],"1993, Bosnia and Herzegovina. A passenger trai...","['Antitalent Produkcija', 'Contrast Films', 'L...",2025-01-16,Not_Found,7.4,1.3K,$0,$0,13,Croatia
498,https://www.imdb.com/title/tt28349451/,The Shadow Strays,"['Action', 'Crime', 'Thriller']","Codename 13, a 17-year-old assassin, is suspen...","['Aurora Ribero', 'Hana Malasan', 'Taskya Namy...","['Indonesian', 'English', 'Japanese', 'Chinese']","Codename 13, a 17-year-old trained assassin is...","['Frontier Pictures', 'XYZ Films']",2024-10-17,Not_Found,6.5,8.6K,$0,$0,144,United States
499,https://www.imdb.com/title/tt31609000/,Anthracite,"['Crime', 'Drama', 'Mystery', 'Thriller']",An old case is wrenched open when a reporter g...,"['Hatik', 'Noémie Schmidt', 'Camille Lou', 'Ni...",['French'],"In 1994, the collective suicide of a sect base...",['Mediawan'],2024-04-10,Not_Found,6.1,4.8K,$0,$0,50,United States
500,https://www.imdb.com/title/tt14203572/,Monsieur Spade,"['Crime', 'Drama', 'Thriller']",The famous detective Sam Spade is now 60 and l...,"['Clive Owen', 'Cara Bossom', 'Denis Ménochet'...","['English', 'French']",Monsieur Spade centers around the infamous pro...,"['Black Bear', 'Haut Et Court Tv']",2024-01-14,Not_Found,6.8,7.4K,$0,$0,Unknown,United States

In [153]:
def convert_to_number(value):
    if isinstance(value, str):
        value = value.replace("$", "").replace("M", "e6").replace("K", "e3")
        try:
            return float(eval(value))
        except:
            return np.nan
    return value

In [154]:
df["Vote_Count"] = df["Vote_Count"].apply(convert_to_number)
df["Budget_USD"] = df["Budget_USD"].apply(convert_to_number)
df["Revenue_$"] = df["Revenue_$"].apply(convert_to_number)
df["Run_Time_Minutes"] = df["Run_Time_Minutes"].apply(pd.to_numeric, errors="coerce")

In [155]:
df

,Home_Page,Movie_Name,Genres,Overview,Cast,Original_Language,Storyline,Production_Company,Release_Date,Tagline,Vote_Average,Vote_Count,Budget_USD,Revenue_$,Run_Time_Minutes,Release_Country
0,https://www.imdb.com/title/tt5040012/,Nosferatu,"['Fantasy', 'Horror', 'Mystery']",A gothic tale of obsession between a haunted y...,"['Lily-Rose Depp', 'Nicholas Hoult', 'Bill Ska...","['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,"['Focus Features', 'Maiden Voyage Pictures', '...",2024-12-25,Succumb to the darkness.,7.3,151000.0,50000000.0,176000000.0,132.0,United States
1,https://www.imdb.com/title/tt20221436/,Emilia Pérez,"['Comedy', 'Crime', 'Drama', 'Musical', 'Thril...",Emilia Pérez follows three remarkable women in...,"['Zoe Saldaña', 'Karla Sofía Gascón', 'Selena ...","['Spanish', 'English']","In modern-day Mexico, overqualified and exploi...","['Why Not Productions', 'Page 114', 'Pathé']",2024-11-13,Not_Found,5.5,71000.0,27300000.0,15000000.0,132.0,United States
2,https://www.imdb.com/title/tt8999762/,The Brutalist,['Drama'],When a visionary architect and his wife flee p...,"['Adrien Brody', 'Felicity Jones', 'Guy Pearce...","['English', 'Hungarian', 'Italian', 'Hebrew', ...",When visionary architect László Toth and his w...,"['Brookstreet Pictures', 'Kaplan Morrison', 'I...",2025-01-24,Welcome to America.,7.9,28000.0,10000000.0,31100000.0,214.0,Canada
3,https://www.imdb.com/title/tt27657135/,Saturday Night,"['Biography', 'Comedy', 'Drama', 'History']","At 11:30pm on October 11th, 1975, a ferocious ...","['Gabriel LaBelle', 'Rachel Sennott', 'Cory Mi...",['English'],"At 11:30pm on October 11, 1975, a ferocious tr...","['Columbia Pictures', 'TSG Entertainment']",2024-10-11,"October 11, 1975, The First Saturday Night Liv...",7.0,26000.0,25000000.0,10000000.0,109.0,United States
4,https://www.imdb.com/title/tt17526714/,The Substance,"['Drama', 'Horror', 'Sci-Fi']",A fading celebrity takes a black-market drug: ...,"['Demi Moore', 'Margaret Qualley', 'Dennis Qua...",['English'],Have you ever dreamed of a better version of y...,"['Working Title Films', 'A Good Story', 'Black...",2024-09-20,"If you follow the instructions, what could go ...",7.3,249000.0,17500000.0,77000000.0,141.0,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,https://www.imdb.com/title/tt28288478/,The Cage,"['Biography', 'Drama', 'Sport']","Dreaming of going pro, a young fighter struggl...","['Franck Gastambide', 'Melvin Boomer', 'Bosh',...",['French'],"Dreaming of going pro, a young fighter struggl...",['Ondamax Films'],2024-11-08,Fight for your dreams.,6.5,2300.0,0.0,0.0,45.0,United States
497,https://www.imdb.com/title/tt20519854/,The Man Who Could Not Remain Silent,"['Short', 'Drama']","1993, Bosnia and Herzegovina. A passenger trai...","['Dragan Micanovic', 'Goran Bogdan', 'Alexis M...",['Croatian'],"1993, Bosnia and Herzegovina. A passenger trai...","['Antitalent Produkcija', 'Contrast Films', 'L...",2025-01-16,Not_Found,7.4,1300.0,0.0,0.0,13.0,Croatia
498,https://www.imdb.com/title/tt28349451/,The Shadow Strays,"['Action', 'Crime', 'Thriller']","Codename 13, a 17-year-old assassin, is suspen...","['Aurora Ribero', 'Hana Malasan', 'Taskya Namy...","['Indonesian', 'English', 'Japanese', 'Chinese']","Codename 13, a 17-year-old trained assassin is...","['Frontier Pictures', 'XYZ Films']",2024-10-17,Not_Found,6.5,8600.0,0.0,0.0,144.0,United States
499,https://www.imdb.com/title/tt31609000/,Anthracite,"['Crime', 'Drama', 'Mystery', 'Thriller']",An old case is wrenched open when a reporter g...,"['Hatik', 'Noémie Schmidt', 'Camille Lou', 'Ni...",['French'],"In 1994, the collective suicide of a sect base...",['Mediawan'],2024-04-10,Not_Found,6.1,4800.0,0.0,0.0,50.0,United States
500,https://www.imdb.com/title/tt14203572/,Monsieur Spade,"['Crime', 'Drama', 'Thriller']",The famous detective Sam Spade is now 60 and l...,"['Clive Owen', 'Cara Bossom', 'Denis Ménochet'...","['English', 'French']",Monsieur Spade centers around the infamous pro...,"['Black Bear', 'Haut Et Court Tv']",2024-01-14,Not_Found,6.8,7400.0,0.0,0.0,NaN,United States

In [156]:
# Разделение на группы
usa_movies = df[df["Release_Country"] == "United States"]["Vote_Average"]
other_movies = df[df["Release_Country"] != "United States"]["Vote_Average"]

In [157]:
usa_movies

0      7.3
1      5.5
3      7.0
4      7.3
5      8.2
      ...
494    6.5
496    6.5
498    6.5
499    6.1
500    6.8
Name: Vote_Average, Length: 414, dtype: float64

In [158]:
other_movies

2      7.9
22     6.2
42     7.3
59     6.5
63     7.3
      ...
481    8.0
486    6.6
490    7.6
495    4.1
497    7.4
Name: Vote_Average, Length: 87, dtype: float64

In [159]:
# Тест 1: Сравнение рейтинга фильмов из США и других стран
t_stat, p_value_1 = stats.ttest_ind(usa_movies, other_movies, equal_var=False, nan_policy="omit")

In [160]:
if p_value_1 <  alpha:
    print("Отклонить нулевую гипотезу (Средний рейтинг фильмов в США не отличается от фильмов других стран)")
else:
  print("Нельзя отклонить нулевую гипотезу(средний рейтинг фильмов из США и других стран примерно одинаков)")

Нельзя отклонить нулевую гипотезу(средний рейтинг фильмов из США и других стран примерно одинаков)

сделать дисперсонный анализ по жанрам и рейтингам 
визуализировать фильмы дни  в месяцы и дни недели(будни/выходные),
Ежедневный график фиьмов 
тест х2 на связь выручки и вышел ли фильм в выхлжной или будний день
попробовать с линейкой сделать, от каких параметров зависит бюджет, кол-во актеров, студий, кол-во опрошенных, продолжительность фильма

In [161]:
# Дисперсионный анализ по жанрам и рейтингам
genre_ratings = df_genres.groupby("Genres")["Vote_Average"].apply(list)
f_val, p_val = stats.f_oneway(*genre_ratings)

print(f"F-статистика = {f_val}, p-значение = {p_val:.3}")
if p_val < 0.05:
    print("Отклоняем нулевую гипотезу: средние рейтинги фильмов значительно различаются между жанрами.")
else:
    print("Не удалось отклонить нулевую гипотезу: средние рейтинги фильмов не имеют значительных различий между жанрами.")

F-статистика = 5.48669568784361, p-значение = 6.55e-16
Отклоняем нулевую гипотезу: средние рейтинги фильмов значительно различаются между жанрами.

In [162]:
genre_ratings

Genres
Action         [6.6, 7.0, 8.2, 6.2, 8.4, 7.2, 5.7, 7.3, 8.5, ...
Adventure      [6.6, 7.0, 6.7, 6.8, 7.9, 8.4, 7.3, 8.5, 8.6, ...
Animation      [8.2, 6.7, 6.8, 7.9, 8.4, 7.8, 7.4, 8.5, 7.5, ...
Biography      [7.0, 7.6, 8.8, 7.1, 7.6, 6.5, 6.5, 7.5, 6.2, ...
Comedy         [5.5, 7.0, 7.7, 7.0, 7.1, 6.8, 5.6, 6.9, 5.7, ...
Crime          [5.5, 7.6, 8.3, 8.2, 6.2, 7.0, 8.6, 7.7, 6.6, ...
Documentary        [8.3, 5.4, 7.0, 7.4, 5.1, 7.5, 7.8, 8.2, 7.2]
Drama          [5.5, 7.9, 7.0, 7.3, 8.2, 6.6, 6.0, 7.6, 7.7, ...
Family         [7.0, 6.7, 6.8, 7.9, 6.8, 5.7, 7.5, 7.6, 6.4, ...
Fantasy        [7.3, 7.0, 7.6, 6.7, 6.8, 7.9, 8.4, 4.7, 7.6, ...
Game-Show                                        [5.6, 6.6, 6.2]
History        [7.0, 8.8, 7.1, 7.5, 8.6, 7.1, 6.5, 6.7, 7.6, ...
Horror         [7.3, 7.3, 6.6, 7.0, 5.6, 7.1, 6.6, 6.8, 6.8, ...
Music          [7.6, 7.6, 6.5, 7.6, 6.3, 6.3, 7.8, 4.7, 7.3, ...
Musical        [5.5, 7.6, 6.7, 6.8, 7.6, 5.2, 5.6, 5.7, 5.5, ...
Mystery        [7.3, 7.6, 6.5, 8.3, 7.4, 4.6, 7.2, 7.0, 4.7, ...
Not_Found      [5.7, 7.8, 6.1, 5.8, 4.6, 7.6, 6.6, 7.7, 7.4, ...
Reality-TV                             [5.6, 6.2, 5.3, 6.6, 6.2]
Romance        [6.0, 7.7, 7.6, 6.4, 7.0, 6.5, 7.1, 7.6, 6.8, ...
Sci-Fi         [7.3, 7.0, 8.2, 7.1, 7.3, 8.5, 7.1, 8.3, 7.6, ...
Short                                                 [7.7, 7.4]
Sport          [7.1, 6.8, 5.7, 7.4, 6.8, 8.1, 8.2, 7.5, 7.9, ...
Thriller       [5.5, 6.0, 6.5, 7.4, 8.2, 7.4, 6.6, 6.2, 7.0, ...
War            [8.6, 6.7, 7.8, 7.5, 6.8, 7.8, 7.0, 6.2, 8.0, ...
Western                                [6.7, 6.9, 7.1, 5.8, 4.1]
Name: Vote_Average, dtype: object

In [163]:
# Визуализация распределения рейтингов по жанрам
fig7 = px.box(df_genres, x="Genres", y="Vote_Average", title="Распределение рейтингов по жанрам", labels={"Genres": "Жанр", "Vote_Average": "Рейтинг"})
fig7.show()

In [164]:
# Дисперсионный анализ по жанрам Drama, Thriller, Comedy, Action
# Гипотеза H0: Средние рейтинги фильмов не различаются между этими жанрами
# Гипотеза H1: Средние рейтинги фильмов различаются между этими жанрами

df["Genres"] = df["Genres"].astype(str).str.strip("[]").str.replace("'", "")
df["Genres"] = df["Genres"].apply(lambda x: x.split(", ") if x != "nan" else [])
df_genres = df.explode("Genres")

selected_genres = ["Drama", "Thriller", "Comedy", "Action"]
df_filtered = df_genres[df_genres["Genres"].isin(selected_genres)]

genre_ratings = df_filtered.groupby("Genres")["Vote_Average"].apply(list)
f_val, p_val = stats.f_oneway(*genre_ratings)

print(f"F-статистика = {f_val:.2f}, p-значение = {p_val:.5f}")

if p_val < 0.05:
    print("Отклоняем нулевую гипотезу: средние рейтинги фильмов значительно различаются между этими жанрами.")
else:
    print("Не удалось отклонить нулевую гипотезу: средние рейтинги фильмов не имеют значительных различий между этими жанрами.")

F-статистика = 11.57, p-значение = 0.00000
Отклоняем нулевую гипотезу: средние рейтинги фильмов значительно различаются между этими жанрами.

In [165]:
# Визуализация распределения рейтингов для выбранных жанров
fig2 = px.box(df_filtered, x="Genres", y="Vote_Average", title="Распределение рейтингов по жанрам (Drama, Thriller, Comedy, Action)", labels={"Genres": "Жанр", "Vote_Average": "Рейтинг"})
fig2.show()

In [166]:

df = pd.read_csv("cleaned_imdb_2024.csv")

In [167]:
# Преобразование даты
df["Release_Date"] = pd.to_datetime(df["Release_Date"], errors="coerce")

# Извлечение дня месяца и дня недели
df["Day_of_Month"] = df["Release_Date"].dt.day
df["Day_of_Week"] = df["Release_Date"].dt.dayofweek

In [168]:
# Определение будних и выходных дней (0-4 — будни, 5-6 — выходные)
df["Weekday_Weekend"] = df["Day_of_Week"].apply(lambda x: "Будни" if x < 5 else "Выходные")

# Визуализация фильмов по дням месяца
fig1 = px.histogram(df, x="Day_of_Month", nbins=31, title="Распределение фильмов по дням месяца", labels={"Day_of_Month": "День месяца"})
fig1.show()

In [169]:
# Визуализация количества фильмов по датам
df["Release_Date_str"] = df["Release_Date"].dt.strftime("%Y-%m-%d")
fig3 = px.line(df.groupby("Release_Date_str").size().reset_index(name="Count"), 
               x="Release_Date_str", y="Count", title="Количество фильмов в течение года", 
               labels={"Release_Date_str": "Дата", "Count": "Количество фильмов"})
fig3.update_xaxes(type="category")
fig3.show()

In [170]:
# Визуализация количества фильмов по дням недели
day_of_week_labels = {0: "Понедельник", 1: "Вторник", 2: "Среда", 3: "Четверг", 4: "Пятница", 5: "Суббота", 6: "Воскресенье"}
df["Day_of_Week_Label"] = df["Day_of_Week"].map(day_of_week_labels)
day_of_week_counts = df["Day_of_Week_Label"].value_counts().reset_index()
day_of_week_counts.columns = ["Day_of_Week", "Count"]
fig5 = px.bar(day_of_week_counts, x="Day_of_Week", y="Count", 
              title="Количество фильмов по дням недели", 
              labels={"Day_of_Week": "День недели", "Count": "Количество фильмов"})
fig5.show()

In [171]:
df2["Revenue_Category"] = pd.qcut(df2["Revenue_$"], q=2, labels=["Низкая", "Высокая"])
df2

,Home_Page,Movie_Name,Genres,Overview,Cast,Original_Language,Storyline,Production_Company,Release_Date,Tagline,Vote_Average,Vote_Count,Budget_USD,Revenue_$,Run_Time_Minutes,Release_Country,Revenue_Category
0,https://www.imdb.com/title/tt5040012/,Nosferatu,"['Fantasy', 'Horror', 'Mystery']",A gothic tale of obsession between a haunted y...,"['Lily-Rose Depp', 'Nicholas Hoult', 'Bill Ska...","['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,"['Focus Features', 'Maiden Voyage Pictures', '...",2024-12-25,Succumb to the darkness.,7.3,151000.0,50000000.0,176000000.0,132.0,United States,Высокая
1,https://www.imdb.com/title/tt20221436/,Emilia Pérez,"['Comedy', 'Crime', 'Drama', 'Musical', 'Thril...",Emilia Pérez follows three remarkable women in...,"['Zoe Saldaña', 'Karla Sofía Gascón', 'Selena ...","['Spanish', 'English']","In modern-day Mexico, overqualified and exploi...","['Why Not Productions', 'Page 114', 'Pathé']",2024-11-13,Not_Found,5.5,71000.0,27300000.0,15000000.0,132.0,United States,Высокая
2,https://www.imdb.com/title/tt8999762/,The Brutalist,['Drama'],When a visionary architect and his wife flee p...,"['Adrien Brody', 'Felicity Jones', 'Guy Pearce...","['English', 'Hungarian', 'Italian', 'Hebrew', ...",When visionary architect László Toth and his w...,"['Brookstreet Pictures', 'Kaplan Morrison', 'I...",2025-01-24,Welcome to America.,7.9,28000.0,10000000.0,31100000.0,214.0,Canada,Высокая
3,https://www.imdb.com/title/tt27657135/,Saturday Night,"['Biography', 'Comedy', 'Drama', 'History']","At 11:30pm on October 11th, 1975, a ferocious ...","['Gabriel LaBelle', 'Rachel Sennott', 'Cory Mi...",['English'],"At 11:30pm on October 11, 1975, a ferocious tr...","['Columbia Pictures', 'TSG Entertainment']",2024-10-11,"October 11, 1975, The First Saturday Night Liv...",7.0,26000.0,25000000.0,10000000.0,109.0,United States,Высокая
4,https://www.imdb.com/title/tt17526714/,The Substance,"['Drama', 'Horror', 'Sci-Fi']",A fading celebrity takes a black-market drug: ...,"['Demi Moore', 'Margaret Qualley', 'Dennis Qua...",['English'],Have you ever dreamed of a better version of y...,"['Working Title Films', 'A Good Story', 'Black...",2024-09-20,"If you follow the instructions, what could go ...",7.3,249000.0,17500000.0,77000000.0,141.0,United States,Высокая
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,https://www.imdb.com/title/tt28288478/,The Cage,"['Biography', 'Drama', 'Sport']","Dreaming of going pro, a young fighter struggl...","['Franck Gastambide', 'Melvin Boomer', 'Bosh',...",['French'],"Dreaming of going pro, a young fighter struggl...",['Ondamax Films'],2024-11-08,Fight for your dreams.,6.5,2300.0,0.0,NaN,45.0,United States,NaN
497,https://www.imdb.com/title/tt20519854/,The Man Who Could Not Remain Silent,"['Short', 'Drama']","1993, Bosnia and Herzegovina. A passenger trai...","['Dragan Micanovic', 'Goran Bogdan', 'Alexis M...",['Croatian'],"1993, Bosnia and Herzegovina. A passenger trai...","['Antitalent Produkcija', 'Contrast Films', 'L...",2025-01-16,Not_Found,7.4,1300.0,0.0,NaN,13.0,Croatia,NaN
498,https://www.imdb.com/title/tt28349451/,The Shadow Strays,"['Action', 'Crime', 'Thriller']","Codename 13, a 17-year-old assassin, is suspen...","['Aurora Ribero', 'Hana Malasan', 'Taskya Namy...","['Indonesian', 'English', 'Japanese', 'Chinese']","Codename 13, a 17-year-old trained assassin is...","['Frontier Pictures', 'XYZ Films']",2024-10-17,Not_Found,6.5,8600.0,0.0,NaN,144.0,United States,NaN
499,https://www.imdb.com/title/tt31609000/,Anthracite,"['Crime', 'Drama', 'Mystery', 'Thriller']",An old case is wrenched open when a reporter g...,"['Hatik', 'Noémie Schmidt', 'Camille Lou', 'Ni...",['French'],"In 1994, the collective suicide of a sect base...",['Mediawan'],2024-04-10,Not_Found,6.1,4800.0,0.0,NaN,50.0,United States,NaN
500,https://www.imdb.com/title/tt14203572/,Monsieur Spade,"['Crime', 'Drama', 'Thriller']",The famous detective Sam Spade is now 60 and l...,"['Clive Owen', 'Cara Bossom', 'Denis Ménochet'...","['English', 'French']",Monsieur Spade centers around the infamous pro...,"['Black Bear', 'Haut Et Court Tv']",2024-01-14,Not_Found,6.8,7400.0,0.0,NaN,NaN,United States,NaN

In [172]:
# Преобразование даты
df2["Release_Date"] = pd.to_datetime(df2["Release_Date"], errors="coerce")

# Извлечение дня месяца и дня недели
df2["Day_of_Month"] = df2["Release_Date"].dt.day
df2["Day_of_Week"] = df2["Release_Date"].dt.dayofweek

# Определение будних и выходных дней (0-4 — будни, 5-6 — выходные)
df2["Weekday_Weekend"] = df2["Day_of_Week"].apply(lambda x: "Будни" if x < 5 else "Выходные")

In [173]:
df2

,Home_Page,Movie_Name,Genres,Overview,Cast,Original_Language,Storyline,Production_Company,Release_Date,Tagline,Vote_Average,Vote_Count,Budget_USD,Revenue_$,Run_Time_Minutes,Release_Country,Revenue_Category,Day_of_Month,Day_of_Week,Weekday_Weekend
0,https://www.imdb.com/title/tt5040012/,Nosferatu,"['Fantasy', 'Horror', 'Mystery']",A gothic tale of obsession between a haunted y...,"['Lily-Rose Depp', 'Nicholas Hoult', 'Bill Ska...","['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,"['Focus Features', 'Maiden Voyage Pictures', '...",2024-12-25,Succumb to the darkness.,7.3,151000.0,50000000.0,176000000.0,132.0,United States,Высокая,25,2,Будни
1,https://www.imdb.com/title/tt20221436/,Emilia Pérez,"['Comedy', 'Crime', 'Drama', 'Musical', 'Thril...",Emilia Pérez follows three remarkable women in...,"['Zoe Saldaña', 'Karla Sofía Gascón', 'Selena ...","['Spanish', 'English']","In modern-day Mexico, overqualified and exploi...","['Why Not Productions', 'Page 114', 'Pathé']",2024-11-13,Not_Found,5.5,71000.0,27300000.0,15000000.0,132.0,United States,Высокая,13,2,Будни
2,https://www.imdb.com/title/tt8999762/,The Brutalist,['Drama'],When a visionary architect and his wife flee p...,"['Adrien Brody', 'Felicity Jones', 'Guy Pearce...","['English', 'Hungarian', 'Italian', 'Hebrew', ...",When visionary architect László Toth and his w...,"['Brookstreet Pictures', 'Kaplan Morrison', 'I...",2025-01-24,Welcome to America.,7.9,28000.0,10000000.0,31100000.0,214.0,Canada,Высокая,24,4,Будни
3,https://www.imdb.com/title/tt27657135/,Saturday Night,"['Biography', 'Comedy', 'Drama', 'History']","At 11:30pm on October 11th, 1975, a ferocious ...","['Gabriel LaBelle', 'Rachel Sennott', 'Cory Mi...",['English'],"At 11:30pm on October 11, 1975, a ferocious tr...","['Columbia Pictures', 'TSG Entertainment']",2024-10-11,"October 11, 1975, The First Saturday Night Liv...",7.0,26000.0,25000000.0,10000000.0,109.0,United States,Высокая,11,4,Будни
4,https://www.imdb.com/title/tt17526714/,The Substance,"['Drama', 'Horror', 'Sci-Fi']",A fading celebrity takes a black-market drug: ...,"['Demi Moore', 'Margaret Qualley', 'Dennis Qua...",['English'],Have you ever dreamed of a better version of y...,"['Working Title Films', 'A Good Story', 'Black...",2024-09-20,"If you follow the instructions, what could go ...",7.3,249000.0,17500000.0,77000000.0,141.0,United States,Высокая,20,4,Будни
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,https://www.imdb.com/title/tt28288478/,The Cage,"['Biography', 'Drama', 'Sport']","Dreaming of going pro, a young fighter struggl...","['Franck Gastambide', 'Melvin Boomer', 'Bosh',...",['French'],"Dreaming of going pro, a young fighter struggl...",['Ondamax Films'],2024-11-08,Fight for your dreams.,6.5,2300.0,0.0,NaN,45.0,United States,NaN,8,4,Будни
497,https://www.imdb.com/title/tt20519854/,The Man Who Could Not Remain Silent,"['Short', 'Drama']","1993, Bosnia and Herzegovina. A passenger trai...","['Dragan Micanovic', 'Goran Bogdan', 'Alexis M...",['Croatian'],"1993, Bosnia and Herzegovina. A passenger trai...","['Antitalent Produkcija', 'Contrast Films', 'L...",2025-01-16,Not_Found,7.4,1300.0,0.0,NaN,13.0,Croatia,NaN,16,3,Будни
498,https://www.imdb.com/title/tt28349451/,The Shadow Strays,"['Action', 'Crime', 'Thriller']","Codename 13, a 17-year-old assassin, is suspen...","['Aurora Ribero', 'Hana Malasan', 'Taskya Namy...","['Indonesian', 'English', 'Japanese', 'Chinese']","Codename 13, a 17-year-old trained assassin is...","['Frontier Pictures', 'XYZ Films']",2024-10-17,Not_Found,6.5,8600.0,0.0,NaN,144.0,United States,NaN,17,3,Будни
499,https://www.imdb.com/title/tt31609000/,Anthracite,"['Crime', 'Drama', 'Mystery', 'Thriller']",An old case is wrenched open when a reporter g...,"['Hatik', 'Noémie Schmidt', 'Camille Lou', 'Ni...",['French'],"In 1994, the collective suicide of a sect base...",['Mediawan'],2024-04-10,Not_Found,6.1,4800.0,0.0,NaN,50.0,United States,NaN,10,2,Будни
500,https://www.imdb.com/title/tt14203572/,Monsieur Spade,"['Crime', 'Drama', 'Thriller']",The famous detective Sam Spade is now 60 and l...,"['Clive Owen', 'Cara Bossom', 'Denis Ménochet'...","['English', 'French']",Monsieur Spade centers around the infamous pro...,"['Black Bear', 'Haut Et Court Tv']",2024-01-14,Not_Found,6.8,7400.0,0.0,NaN,NaN,United States,NaN,14,6,Выходные

In [174]:
# Создаем таблицу сопряженности
contingency_table = pd.crosstab(df2["Revenue_Category"], df2["Weekday_Weekend"])

In [175]:
# Выполняем тест хи-квадрат
chi2, p, dof, expected = stats.chi2_contingency(contingency_table)
print(f"Хи-квадрат: {chi2}, p-значение: {p}")

Хи-квадрат: 0.0, p-значение: 1.0

In [176]:
alpha = 0.05
if p < alpha:
    print("Гипотеза H₀ отвергается: существует статистически значимая связь между выручкой и днем выхода фильма.")
else:
    print("Гипотеза H₀ не отвергается: статистически значимой связи между выручкой и днем выхода фильма нет.")

Гипотеза H₀ не отвергается: статистически значимой связи между выручкой и днем выхода фильма нет.

In [177]:
fig2 = px.bar(df2["Weekday_Weekend"].value_counts().reset_index(), x="count", y="Weekday_Weekend", 
              title="Количество фильмов, выпущенных в будни и выходные", labels={"index": "День недели", "Weekday_Weekend": "Количество фильмов"})
fig2.show()

In [178]:
fig = px.imshow(contingency_table, 
                labels={'x': 'День выхода фильма', 'y': 'Категория выручки', 'color': 'Частота'},
                color_continuous_scale='Blues',
                title="Связь между выручкой и днем выхода фильма")

fig.update_layout(
    xaxis_title="День выхода фильма",
    yaxis_title="Категория выручки",
)

fig.show()

In [179]:
df = df1
# Считаем количество актёров в каждом фильме
df["Actor_Count"] = df["Cast"].apply(len)

In [180]:
df

,Home_Page,Movie_Name,Genres,Overview,Cast,Original_Language,Storyline,Production_Company,Release_Date,Tagline,...,Vote_Count,Budget_USD,Revenue_$,Run_Time_Minutes,Release_Country,Revenue_Category,Day_of_Month,Day_of_Week,Weekday_Weekend,Actor_Count
0,https://www.imdb.com/title/tt5040012/,Nosferatu,"['Fantasy', 'Horror', 'Mystery']",A gothic tale of obsession between a haunted y...,"['Lily-Rose Depp', 'Nicholas Hoult', 'Bill Ska...","['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,"['Focus Features', 'Maiden Voyage Pictures', '...",2024-12-25,Succumb to the darkness.,...,151000.0,50000000.0,176000000.0,132.0,United States,Высокая,25,2,Будни,329
1,https://www.imdb.com/title/tt20221436/,Emilia Pérez,"['Comedy', 'Crime', 'Drama', 'Musical', 'Thril...",Emilia Pérez follows three remarkable women in...,"['Zoe Saldaña', 'Karla Sofía Gascón', 'Selena ...","['Spanish', 'English']","In modern-day Mexico, overqualified and exploi...","['Why Not Productions', 'Page 114', 'Pathé']",2024-11-13,Not_Found,...,71000.0,27300000.0,15000000.0,132.0,United States,Высокая,13,2,Будни,353
2,https://www.imdb.com/title/tt8999762/,The Brutalist,['Drama'],When a visionary architect and his wife flee p...,"['Adrien Brody', 'Felicity Jones', 'Guy Pearce...","['English', 'Hungarian', 'Italian', 'Hebrew', ...",When visionary architect László Toth and his w...,"['Brookstreet Pictures', 'Kaplan Morrison', 'I...",2025-01-24,Welcome to America.,...,28000.0,10000000.0,31100000.0,214.0,Canada,Высокая,24,4,Будни,313
3,https://www.imdb.com/title/tt27657135/,Saturday Night,"['Biography', 'Comedy', 'Drama', 'History']","At 11:30pm on October 11th, 1975, a ferocious ...","['Gabriel LaBelle', 'Rachel Sennott', 'Cory Mi...",['English'],"At 11:30pm on October 11, 1975, a ferocious tr...","['Columbia Pictures', 'TSG Entertainment']",2024-10-11,"October 11, 1975, The First Saturday Night Liv...",...,26000.0,25000000.0,10000000.0,109.0,United States,Высокая,11,4,Будни,319
4,https://www.imdb.com/title/tt17526714/,The Substance,"['Drama', 'Horror', 'Sci-Fi']",A fading celebrity takes a black-market drug: ...,"['Demi Moore', 'Margaret Qualley', 'Dennis Qua...",['English'],Have you ever dreamed of a better version of y...,"['Working Title Films', 'A Good Story', 'Black...",2024-09-20,"If you follow the instructions, what could go ...",...,249000.0,17500000.0,77000000.0,141.0,United States,Высокая,20,4,Будни,330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,https://www.imdb.com/title/tt28288478/,The Cage,"['Biography', 'Drama', 'Sport']","Dreaming of going pro, a young fighter struggl...","['Franck Gastambide', 'Melvin Boomer', 'Bosh',...",['French'],"Dreaming of going pro, a young fighter struggl...",['Ondamax Films'],2024-11-08,Fight for your dreams.,...,2300.0,0.0,NaN,45.0,United States,NaN,8,4,Будни,311
497,https://www.imdb.com/title/tt20519854/,The Man Who Could Not Remain Silent,"['Short', 'Drama']","1993, Bosnia and Herzegovina. A passenger trai...","['Dragan Micanovic', 'Goran Bogdan', 'Alexis M...",['Croatian'],"1993, Bosnia and Herzegovina. A passenger trai...","['Antitalent Produkcija', 'Contrast Films', 'L...",2025-01-16,Not_Found,...,1300.0,0.0,NaN,13.0,Croatia,NaN,16,3,Будни,224
498,https://www.imdb.com/title/tt28349451/,The Shadow Strays,"['Action', 'Crime', 'Thriller']","Codename 13, a 17-year-old assassin, is suspen...","['Aurora Ribero', 'Hana Malasan', 'Taskya Namy...","['Indonesian', 'English', 'Japanese', 'Chinese']","Codename 13, a 17-year-old trained assassin is...","['Frontier Pictures', 'XYZ Films']",2024-10-17,Not_Found,...,8600.0,0.0,NaN,144.0,United States,NaN,17,3,Будни,330
499,https://www.imdb.com/title/tt31609000/,Anthracite,"['Crime', 'Drama', 'Mystery', 'Thriller']",An old case is wrenched open when a reporter g...,"['Hatik', 'Noémie Schmidt', 'Camille Lou', 'Ni...",['French'],"In 1994, the collective suicide of a sect base...",['Mediawan'],2024-04-10,Not_Found,...,4800.0,0.0,NaN,50.0,United States,NaN,10,2,Будни,318
500,https://www.imdb.com/title/tt14203572/,Monsieur Spade,"['Crime', 'Drama', 'Thriller']",The famous detective Sam Spade is now 60 and l...,"['Clive Owen', 'Cara Bossom', 'Denis Ménochet'...","['English', 'French']",Monsieur Spade centers around the infamous pro...,"['Black Bear', 'Haut Et Court Tv']",2024-01-14,Not_Found,...,7400.0,0.0,NaN,NaN,United States,NaN,14,6,Выходные,312

In [181]:
# Удаляем пропуски в бюджете и фильтруем по положительным значениям
budget_df = df[["Budget_USD", "Actor_Count"]].dropna()
budget_df = budget_df[budget_df["Budget_USD"] > 0]

In [182]:
budget_df

     Budget_USD  Actor_Count
0    50000000.0          329
1    27300000.0          353
2    10000000.0          313
3    25000000.0          319
4    17500000.0          330
..          ...          ...
419  83000000.0          290
432  13000000.0          296
461  22000000.0          331
482    650000.0          308
495   7000000.0          320

[119 rows x 2 columns]

In [183]:
fig3 = px.scatter(budget_df, x="Actor_Count", y="Budget_USD",
                 title="Зависимость бюджета фильма от количества актёров",
                 labels={"Actor_Count": "Количество актёров", "Budget_USD": "Бюджет"},
                 )
fig3.show()

In [184]:
df["Production_Company"] = df["Production_Company"].astype(str).str.strip("[]").str.replace("'", "")
df["Production_Company"] = df["Production_Company"].apply(lambda x: x.split(", ") if x != "nan" else [])
df_companies = df.explode("Production_Company")
df_companies

,Home_Page,Movie_Name,Genres,Overview,Cast,Original_Language,Storyline,Production_Company,Release_Date,Tagline,...,Vote_Count,Budget_USD,Revenue_$,Run_Time_Minutes,Release_Country,Revenue_Category,Day_of_Month,Day_of_Week,Weekday_Weekend,Actor_Count
0,https://www.imdb.com/title/tt5040012/,Nosferatu,"['Fantasy', 'Horror', 'Mystery']",A gothic tale of obsession between a haunted y...,"['Lily-Rose Depp', 'Nicholas Hoult', 'Bill Ska...","['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,Focus Features,2024-12-25,Succumb to the darkness.,...,151000.0,50000000.0,176000000.0,132.0,United States,Высокая,25,2,Будни,329
0,https://www.imdb.com/title/tt5040012/,Nosferatu,"['Fantasy', 'Horror', 'Mystery']",A gothic tale of obsession between a haunted y...,"['Lily-Rose Depp', 'Nicholas Hoult', 'Bill Ska...","['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,Maiden Voyage Pictures,2024-12-25,Succumb to the darkness.,...,151000.0,50000000.0,176000000.0,132.0,United States,Высокая,25,2,Будни,329
0,https://www.imdb.com/title/tt5040012/,Nosferatu,"['Fantasy', 'Horror', 'Mystery']",A gothic tale of obsession between a haunted y...,"['Lily-Rose Depp', 'Nicholas Hoult', 'Bill Ska...","['English', 'German', 'Romanian', 'Russian']",A gothic tale of obsession between a haunted y...,Studio 8,2024-12-25,Succumb to the darkness.,...,151000.0,50000000.0,176000000.0,132.0,United States,Высокая,25,2,Будни,329
1,https://www.imdb.com/title/tt20221436/,Emilia Pérez,"['Comedy', 'Crime', 'Drama', 'Musical', 'Thril...",Emilia Pérez follows three remarkable women in...,"['Zoe Saldaña', 'Karla Sofía Gascón', 'Selena ...","['Spanish', 'English']","In modern-day Mexico, overqualified and exploi...",Why Not Productions,2024-11-13,Not_Found,...,71000.0,27300000.0,15000000.0,132.0,United States,Высокая,13,2,Будни,353
1,https://www.imdb.com/title/tt20221436/,Emilia Pérez,"['Comedy', 'Crime', 'Drama', 'Musical', 'Thril...",Emilia Pérez follows three remarkable women in...,"['Zoe Saldaña', 'Karla Sofía Gascón', 'Selena ...","['Spanish', 'English']","In modern-day Mexico, overqualified and exploi...",Page 114,2024-11-13,Not_Found,...,71000.0,27300000.0,15000000.0,132.0,United States,Высокая,13,2,Будни,353
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,https://www.imdb.com/title/tt28349451/,The Shadow Strays,"['Action', 'Crime', 'Thriller']","Codename 13, a 17-year-old assassin, is suspen...","['Aurora Ribero', 'Hana Malasan', 'Taskya Namy...","['Indonesian', 'English', 'Japanese', 'Chinese']","Codename 13, a 17-year-old trained assassin is...",Frontier Pictures,2024-10-17,Not_Found,...,8600.0,0.0,NaN,144.0,United States,NaN,17,3,Будни,330
498,https://www.imdb.com/title/tt28349451/,The Shadow Strays,"['Action', 'Crime', 'Thriller']","Codename 13, a 17-year-old assassin, is suspen...","['Aurora Ribero', 'Hana Malasan', 'Taskya Namy...","['Indonesian', 'English', 'Japanese', 'Chinese']","Codename 13, a 17-year-old trained assassin is...",XYZ Films,2024-10-17,Not_Found,...,8600.0,0.0,NaN,144.0,United States,NaN,17,3,Будни,330
499,https://www.imdb.com/title/tt31609000/,Anthracite,"['Crime', 'Drama', 'Mystery', 'Thriller']",An old case is wrenched open when a reporter g...,"['Hatik', 'Noémie Schmidt', 'Camille Lou', 'Ni...",['French'],"In 1994, the collective suicide of a sect base...",Mediawan,2024-04-10,Not_Found,...,4800.0,0.0,NaN,50.0,United States,NaN,10,2,Будни,318
500,https://www.imdb.com/title/tt14203572/,Monsieur Spade,"['Crime', 'Drama', 'Thriller']",The famous detective Sam Spade is now 60 and l...,"['Clive Owen', 'Cara Bossom', 'Denis Ménochet'...","['English', 'French']",Monsieur Spade centers around the infamous pro...,Black Bear,2024-01-14,Not_Found,...,7400.0,0.0,NaN,NaN,United States,NaN,14,6,Выходные,312
500,https://www.imdb.com/title/tt14203572/,Monsieur Spade,"['Crime', 'Drama', 'Thriller']",The famous detective Sam Spade is now 60 and l...,"['Clive Owen', 'Cara Bossom', 'Denis Ménochet'...","['English', 'French']",Monsieur Spade centers around the infamous pro...,Haut Et Court Tv,2024-01-14,Not_Found,...,7400.0,0.0,NaN,NaN,United States,NaN,14,6,Выходные,312

In [185]:
company_budget = df_companies.groupby("Production_Company")["Budget_USD"].sum().reset_index()
company_budget = company_budget.sort_values(by="Budget_USD", ascending=False).head(20)
company_budget

                        Production_Company    Budget_USD
921                           Warner Bros.  1.068000e+09
219                      Columbia Pictures  7.370000e+08
666                     Paramount Pictures  6.130000e+08
918                   Walt Disney Pictures  5.500000e+08
6                     20th Century Studios  4.700000e+08
270              Domain Entertainment (II)  4.580000e+08
895                     Universal Pictures  4.200000e+08
205               Chris Morgan Productions  3.500000e+08
917          Walt Disney Animation Studios  3.500000e+08
49                      Amazon MGM Studios  3.500000e+08
771                Seven Bucks Productions  3.500000e+08
711  Québec Production Services Tax Credit  3.380000e+08
757                 Scott Free Productions  3.300000e+08
513                Legendary Entertainment  3.250000e+08
569                         Maximum Effort  3.100000e+08
562                   Marvel Entertainment  3.100000e+08
271    Don Simpson/Jerry Bruckheimer Films  2.500000e+08
727                        Red Wagon Films  2.500000e+08
72                        Arad Productions  2.350000e+08
521                              Lionsgate  2.290000e+08

In [186]:
fig4 = px.bar(company_budget, x="Production_Company", y="Budget_USD",
             title="Топ 20 компаний по суммарному бюджету фильмов",
             labels={"Production_Company": "Кинокомпания", "Budget_USD": "Суммарный бюджет"})
fig4.update_layout(xaxis_tickangle=-45)
fig4.show()

In [187]:
df["Studio_Count"] = df["Production_Company"].apply(len)
studio_budget_df = df[["Studio_Count", "Budget_USD"]].dropna()
studio_budget_df = studio_budget_df[studio_budget_df["Budget_USD"] > 0]
studio_budget_df

     Studio_Count  Budget_USD
0               3  50000000.0
1               3  27300000.0
2               3  10000000.0
3               2  25000000.0
4               3  17500000.0
..            ...         ...
419             2  83000000.0
432             3  13000000.0
461             2  22000000.0
482             2    650000.0
495             3   7000000.0

[119 rows x 2 columns]

In [188]:
fig5 = px.scatter(studio_budget_df, x="Studio_Count", y="Budget_USD",
                 title="Зависимость бюджета фильма от количества студий",
                 labels={"Studio_Count": "Количество студий", "Budget_USD": "Бюджет"},
                 )
fig5.show()

In [189]:
# --- ЛИНЕЙНАЯ РЕГРЕССИЯ: Зависимость Vote_Average от Budget --- ЕЁ НЕТ
regression_df = df[["Vote_Average", "Budget_USD"]].dropna()
regression_df = regression_df[regression_df["Budget_USD"] > 0]
regression_df

     Vote_Average  Budget_USD
0             7.3  50000000.0
1             5.5  27300000.0
2             7.9  10000000.0
3             7.0  25000000.0
4             7.3  17500000.0
..            ...         ...
419           5.3  83000000.0
432           7.4  13000000.0
461           4.2  22000000.0
482           5.5    650000.0
495           4.1   7000000.0

[119 rows x 2 columns]

In [190]:
# Проверка нормальности остатков: тест Шапиро-Уилка
X = regression_df["Budget_USD"]
y = regression_df["Vote_Average"]
X = sm.add_constant(X)
model = sm.OLS(y, X).fit()
residuals = model.resid

shapiro_stat, shapiro_p = shapiro(residuals)
print(f"Shapiro-Wilk test: статистика = {shapiro_stat:.4f}, p-значение = {shapiro_p:.5f}")

if shapiro_p > 0.05:
    print("Остатки распределены нормально — условие линейной регрессии выполняется.")
else:
    print("Остатки не распределены нормально — возможны нарушения в линейной модели.")

Shapiro-Wilk test: статистика = 0.9639, p-значение = 0.00277
Остатки не распределены нормально — возможны нарушения в линейной модели.

In [191]:
# Итоги регрессии
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:           Vote_Average   R-squared:                       0.027
Model:                            OLS   Adj. R-squared:                  0.018
Method:                 Least Squares   F-statistic:                     3.188
Date:                Sat, 12 Apr 2025   Prob (F-statistic):             0.0768
Time:                        09:56:42   Log-Likelihood:                -177.20
No. Observations:                 119   AIC:                             358.4
Df Residuals:                     117   BIC:                             364.0
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          6.1309      0.135     45.457      0.000       5.864       6.398
Budget_USD  2.809e-09   1.57e-09      1.785      0.077   -3.07e-10    5.92e-09
==============================================================================
Omnibus:                       21.901   Durbin-Watson:                   1.661
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               41.531
Skew:                          -0.777   Prob(JB):                     9.59e-10
Kurtosis:                       5.442   Cond. No.                     1.17e+08
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.17e+08. This might indicate that there are
strong multicollinearity or other numerical problems.

In [192]:
# Визуализация регрессии
fig6 = px.scatter(regression_df, x="Budget_USD", y="Vote_Average",
                 title="Линейная регрессия: Рейтинг фильма от бюджета",
                 labels={"Budget_USD": "Бюджет", "Vote_Average": "Рейтинг"},
                 trendline="ols")
fig6.show()

In [193]:
# --- ЛИНЕЙНАЯ РЕГРЕССИЯ: Зависимость количества проголосовавших от средней оценки ---
vc_reg_df = df[["Vote_Count", "Vote_Average"]].dropna()
vc_reg_df = vc_reg_df[vc_reg_df["Vote_Count"] > 0]

In [194]:
X_vc = sm.add_constant(vc_reg_df["Vote_Average"])
y_vc = vc_reg_df["Vote_Count"]
model_vc = sm.OLS(y_vc, X_vc).fit()
residuals_vc = model_vc.resid

In [195]:
shapiro_stat_vc, shapiro_p_vc = shapiro(residuals_vc)
print(f"Shapiro-Wilk test (Vote_Count от Vote_Average): статистика = {shapiro_stat_vc:.4f}, p-значение = {shapiro_p_vc:.5f}")

if shapiro_p_vc > 0.05:
    print("Остатки распределены нормально — условие линейной регрессии выполняется.")
else:
    print("Остатки не распределены нормально — возможны нарушения в линейной модели.")

Shapiro-Wilk test (Vote_Count от Vote_Average): статистика = 0.5934, p-значение = 0.00000
Остатки не распределены нормально — возможны нарушения в линейной модели.

In [196]:
print(model_vc.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:             Vote_Count   R-squared:                       0.025
Model:                            OLS   Adj. R-squared:                  0.023
Method:                 Least Squares   F-statistic:                     12.99
Date:                Sat, 12 Apr 2025   Prob (F-statistic):           0.000344
Time:                        09:56:42   Log-Likelihood:                -6159.4
No. Observations:                 500   AIC:                         1.232e+04
Df Residuals:                     498   BIC:                         1.233e+04
Df Model:                           1
Covariance Type:            nonrobust
================================================================================
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const        -2.242e+04   1.48e+04     -1.519      0.129   -5.14e+04    6578.559
Vote_Average  7985.6533   2215.256      3.605      0.000    3633.254    1.23e+04
==============================================================================
Omnibus:                      503.488   Durbin-Watson:                   1.608
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            22075.728
Skew:                           4.469   Prob(JB):                         0.00
Kurtosis:                      34.301   Cond. No.                         41.4
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [197]:
fig7 = px.scatter(vc_reg_df, x="Vote_Average", y="Vote_Count",
                 title="Линейная регрессия: Кол-во проголосовавших от средней оценки",
                 labels={"Vote_Average": "Средняя оценка", "Vote_Count": "Кол-во голосов"},
                 )
fig7.show()

In [198]:
# --- КОРРЕЛЯЦИОННЫЙ БОКСПЛОТ ---
# Только числовые столбцы
numeric_df = df.select_dtypes(include='number')
fig8 = px.imshow(numeric_df.corr(),
                 title="Корреляционная матрица",
                 color_continuous_scale='RdBu_r',
                 text_auto=True,
                 aspect="auto")
fig8.show()

In [199]:
# --- ЛИНЕЙНАЯ ЗАВИСИМОСТЬ: Бюджет от количества проголосовавших ---
budget_votes_df = df[["Budget_USD", "Vote_Count"]].dropna()
budget_votes_df = budget_votes_df[(budget_votes_df["Budget_USD"] > 0) & (budget_votes_df["Vote_Count"] > 0)]

fig9 = px.scatter(budget_votes_df, x="Vote_Count", y="Budget_USD",
                  title="Зависимость бюджета фильма от количества проголосовавших",
                  labels={"Vote_Count": "Количество голосов", "Budget_USD": "Бюджет"},
                  trendline="ols")
fig9.show()

In [200]:
# --- ЛИНЕЙНАЯ РЕГРЕССИЯ: Бюджет от продолжительности фильма ---
budget_runtime_df = df[["Budget_USD", "Run_Time_Minutes"]].dropna()
budget_runtime_df = budget_runtime_df[(budget_runtime_df["Budget_USD"] > 0) & (budget_runtime_df["Run_Time_Minutes"] > 0)]

X_rt = sm.add_constant(budget_runtime_df["Run_Time_Minutes"])
y_rt = budget_runtime_df["Budget_USD"]
model_rt = sm.OLS(y_rt, X_rt).fit()
residuals_rt = model_rt.resid

shapiro_stat_rt, shapiro_p_rt = shapiro(residuals_rt)
print(f"\nShapiro-Wilk test (Budget от Runtime): статистика = {shapiro_stat_rt:.4f}, p-значение = {shapiro_p_rt:.5f}")

if shapiro_p_rt > 0.05:
    print("Остатки распределены нормально — условие линейной регрессии выполняется.")
else:
    print("Остатки не распределены нормально — возможны нарушения в линейной модели.")

print(model_rt.summary())

fig10 = px.scatter(budget_runtime_df, x="Run_Time_Minutes", y="Budget_USD",
                  title="Линейная регрессия: Бюджет от продолжительности фильма",
                  labels={"Run_Time_Minutes": "Продолжительность (мин)", "Budget_USD": "Бюджет"},
                  trendline="ols")
fig10.show()

Shapiro-Wilk test (Budget от Runtime): статистика = 0.8669, p-значение = 0.00000
Остатки не распределены нормально — возможны нарушения в линейной модели.
                            OLS Regression Results
==============================================================================
Dep. Variable:             Budget_USD   R-squared:                       0.056
Model:                            OLS   Adj. R-squared:                  0.048
Method:                 Least Squares   F-statistic:                     6.869
Date:                Sat, 12 Apr 2025   Prob (F-statistic):            0.00995
Time:                        09:56:42   Log-Likelihood:                -2283.4
No. Observations:                 118   AIC:                             4571.
Df Residuals:                     116   BIC:                             4576.
Df Model:                           1
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
const            -1.712e+07   2.94e+07     -0.582      0.562   -7.54e+07    4.12e+07
Run_Time_Minutes  6.431e+05   2.45e+05      2.621      0.010    1.57e+05    1.13e+06
==============================================================================
Omnibus:                       45.636   Durbin-Watson:                   1.910
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              104.476
Skew:                           1.559   Prob(JB):                     2.06e-23
Kurtosis:                       6.396   Cond. No.                         620.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [201]:
df["Budget_USD"] = pd.to_numeric(df["Budget_USD"], errors="coerce")
df = df.dropna(subset=["Budget_USD", "Cast"])

    # Посчитаем количество актеров в каждом фильме
    # Предполагается, что Cast — это строка или список
df["Actor_Count"] = df["Cast"].apply(lambda x: len(eval(x)) if isinstance(x, str) else len(x))

    # Построим scatter plot зависимости количества актеров от бюджета
fig6 = px.scatter(df, x="Actor_Count", y="Budget_USD", 
                      title="Зависимость бюджета от количества актеров",
                      labels={"Actor_Count": "Количество актеров", "Budget_USD": "Бюджет фильма"})
fig6.show()

In [202]:
# Удаляем квадратные скобки перед разделением
df['Cast'] = df['Cast'].str.replace(r'[\[\]]', '', regex=True).str.split(',')
    
# Создаем отдельный датафрейм с развернутыми актерами
actor_budget = df.explode('Cast')
actor_budget['Cast'] = actor_budget['Cast'].str.strip()

# Удаляем строки с пропущенными значениями
actor_budget = actor_budget.dropna(subset=['Cast'])

# Группируем по актеру и считаем суммарный бюджет
actor_summary = actor_budget.groupby('Cast', as_index=False)['Budget_USD'].sum()

# Сортируем по убыванию бюджета и берем топ-30
top_actors = actor_summary.sort_values('Budget_USD', ascending=False).head(30)

# Строим график
fig = px.bar(top_actors,
             x='Budget_USD',
             y='Cast',
             orientation='h',
             title='Топ 30 актеров по суммарному бюджету фильмов',
             labels={'Cast': 'Актер', 'Budget_USD': 'Суммарный бюджет фильмов (USD)'},
             color='Budget_USD',
             color_continuous_scale='deep')

fig.update_layout(
    yaxis={'categoryorder': 'total ascending'},
    height=700,
    coloraxis_showscale=False
)


fig.show()

In [203]:
actor_summary.sort_values('Budget_USD', ascending=False).head(30)

                        Cast   Budget_USD
1507           'Chris Evans'  550000000.0
4147        'Kiernan Shipka'  506800000.0
2162        'Dwayne Johnson'  500000000.0
2948          'Henry Cavill'  460000000.0
3132          'J.K. Simmons'  380000000.0
2586        'Fred Hechinger'  360000000.0
5521            'Nick Kroll'  350000000.0
7561            'Wyatt Hunt'  350000000.0
6410       'Samantha Benson'  350000000.0
4239       'Kristofer Hivju'  350000000.0
1616        'Clayton Cooper'  350000000.0
1630      'Cody Easterbrook'  350000000.0
4305            'Lanz Duffy'  350000000.0
820      'Ashleigh Domangue'  350000000.0
4722          'Makana David'  350000000.0
1124           'Bonnie Hunt'  350000000.0
4756     'Marc Evan Jackson'  350000000.0
4616              'Lucy Liu'  350000000.0
4924  'Mary Elizabeth Ellis'  350000000.0
7506         'Wesley Kimmel'  350000000.0
5802          'Pedro Pascal'  328000000.0
1398        'Channing Tatum'  320000000.0
3761          'Joseph Quinn'  317000000.0
772          'Ariana DeBose'  310000000.0
6333         'Ryan Reynolds'  310000000.0
5022                'Matuse'  293000000.0
6903          'Steve Coogan'  290000000.0
452           'Alyla Browne'  290000000.0
98    'Aaron Taylor-Johnson'  285000000.0
5964          'Rachel House'  285000000.0